// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: AGPL-3.0-only
// Dual-licensed; see the NOTICE file for licensing and any additional terms.

/**
 * @fileoverview Freshness pin for the committed two-surface `dist/` tree of
 * `@awacloud/odf`. The tree is generated by `tools/generate-bundles.mjs` and
 * goes stale on any `src/` change that reaches a bundle root's closure, while
 * `dist-bundles.integration.test.js` stays green (it only imports the committed
 * artefacts). This test regenerates both variants (`bundled` -> `dist/standalone`,
 * `package` -> `dist/build`) in a temp dir with the same generator call the
 * driver makes, and compares each of the 18 committed `.js` files, minus the
 * licence banner, byte-for-byte against the fresh output. A stale tree fails
 * naming the root and the surface.
 *
 * Scope notes:
 *
 *   - `.min.js` is NOT regenerated here: it needs one `Bun.build` run per file
 *     (18 runs) and is a deterministic function of the `.js` the driver writes
 *     in the same pass, so `.js` drift implies `.min.js` drift. The `.meta.json`
 *     `bytes.dev` / `bytes.min` are instead checked against the on-disk sizes.
 *   - The dist files are read as TEXT, never imported: importing raw per-root
 *     `dist/**` inflates the coverage denominator (see `awa.coverageBasis`).
 *   - The generator inlines factories through `Function.prototype.toString()`,
 *     which returns the source AS THE RUNTIME TRANSPILED IT. Bun transpiles with
 *     syntax minification in a plain `bun test` (`return !0`) but not under
 *     `--coverage` (`return true`), so every inlined fw factory differs from the
 *     committed text by transpiler mode alone. The committed tree is the plain
 *     mode's output (`bun run gen:bundles`); the coverage run therefore skips the
 *     byte comparison (detected by the canary below), and the plain `bun test`
 *     leg enforces it. The plain-mode guarantee itself is pinned by a
 *     child-process leg that runs in BOTH modes: a plain child process must read
 *     the canary as `true`, so the byte legs cannot all skip silently; a final
 *     leg checks they ran exactly when the canary said they would.
 *
 * @module odf/tests/dist-freshness.integration.test
 */
import { describe, test, expect, afterAll } from 'bun:test';
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

import { generatePrebuilds, kebabCase, stripBundleSuffix } from '@awacloud/tool-prebuild-generator';
import * as odf from '../src/main.js';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');
const DRIVER = 'packages/front/office/odf/tools/generate-bundles.mjs';

// Roots derived like the driver: the bare cores (head of each bundle chain)
// plus one id per bundle entry.
const bundleByName = Object.create(null);
for (const b of odf.bundle) bundleByName[b.name] = b;

/** Follow `dependencies[0]` while it names another bundle; return the bare core. */
function coreOf(b) {
    const head = b.dependencies[0];
    return bundleByName[head] ? coreOf(bundleByName[head]) : head;
}

const roots = new Set();
for (const b of odf.bundle) roots.add(coreOf(b));
for (const b of odf.bundle) roots.add(kebabCase(stripBundleSuffix(b.name)));

// Canary: true when this runtime transpiles like `bun run gen:bundles` does.
// (The literal `true` is rewritten to `!0` only under the plain transpiler.)
const CANONICAL_TRANSPILE = String(function () { if (arguments.length) { return true; } return false; }).includes('!0');

// Single source of the canary: the `CANONICAL_TRANSPILE` line above. The
// child-process leg runs that very text in a plain runtime, so the in-process
// canary and the child's cannot diverge.
const CANARY_EXPR = /^const CANONICAL_TRANSPILE = (.*);\s*$/m.exec(readFileSync(fileURLToPath(import.meta.url), 'utf8'))?.[1];

/** Byte legs that actually executed (bumped first in each leg body). */
let executed = 0;

/** [generator variant, committed surface directory]. */
const SURFACES = [['bundled', 'standalone'], ['package', 'build']];

const tmp = mkdtempSync(join(tmpdir(), 'odf-fresh-'));
afterAll(() => rmSync(tmp, { recursive: true, force: true }));

for (const [variant] of SURFACES) {
    if (!CANONICAL_TRANSPILE) break;
    generatePrebuilds({
        packageMain: odf,
        outDir: join(tmp, variant),
        packageLabel: 'odf',
        variants: [variant],
        closureCaptures: {},
        driver: DRIVER
    });
}

describe('odf committed dist is fresh', () => {
    for (const [variant, dir] of SURFACES) {
        for (const root of roots) {
            test.skipIf(!CANONICAL_TRANSPILE)(`${dir}/${root}.js is fresh`, () => {
                executed++;
                const committed = readFileSync(join(PKG, 'dist', dir, `${root}.js`), 'utf8');
                const generated = readFileSync(join(tmp, variant, `${root}-${variant}.js`), 'utf8');
                expect(committed.startsWith('/*!')).toBe(true);     // licence banner at byte 0
                expect(committed.endsWith(generated)).toBe(true);   // banner + generated text, nothing else
                const meta = JSON.parse(readFileSync(join(PKG, 'dist', dir, `${root}.meta.json`), 'utf8'));
                expect(meta.bytes.dev).toBe(Buffer.byteLength(committed, 'utf8'));
                expect(meta.bytes.min).toBe(readFileSync(join(PKG, 'dist', dir, `${root}.min.js`)).byteLength);
            });
        }
    }

    test('the committed root set equals the derived one', () => {
        for (const [, dir] of SURFACES) {
            const onDisk = readdirSync(join(PKG, 'dist', dir))
                .filter(f => f.endsWith('.js') && !f.endsWith('.min.js') && f !== 'index.js')
                .map(f => f.slice(0, -3))
                .sort();
            expect(onDisk).toEqual([...roots].sort());
        }
    });

    test('the generator runtime transpiles canonically (byte legs cannot skip silently)', () => {
        expect(typeof CANARY_EXPR).toBe('string');
        // A plain child process is the generator's runtime (`bun run gen:bundles`),
        // whatever mode this test process runs in (coverage changes the transpiler).
        const child = Bun.spawnSync([process.execPath, '-e', `console.log(${CANARY_EXPR})`]);
        const out = child.stdout.toString().trim();
        if (out !== 'true') {
            throw new Error(
                'plain-mode Function.prototype.toString changed: the committed dist and the '
                + `freshness legs need re-deriving (child exit ${child.exitCode}, stdout "${out}", `
                + `stderr "${child.stderr.toString().trim()}")`
            );
        }
        expect(out).toBe('true');
    }, 30000);

    // Declared LAST: bun runs a file's tests in declaration order.
    test('the byte legs ran exactly when the canary said they would', () => {
        expect(executed).toBe(CANONICAL_TRANSPILE ? SURFACES.length * roots.size : 0);
    });
});
