// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: Apache-2.0

/**
 * @fileoverview Brotli static word dictionary loader (RFC 7932 Appendix A).
 *
 * Lazy-load wrapper around the **122 784-byte** dictionary binary. The blob
 * itself lives as a raw `.bin` asset next to this module
 * (`brotli_dict.bin`), **not** inlined as base64 - embedding it in JS would
 * add ~33% overhead (163 712 chars) and prevent the browser cache from
 * sharing the asset across page loads or workers.
 *
 * The factory exposes:
 *
 * - `setBlob(buf)` - synchronous: validate and accept a pre-loaded blob.
 *   Used by Node/Bun tests (read the `.bin` via `fs`) and by consumers
 *   that have already fetched the bytes through their own pipeline.
 * - `load(url)` - async: `fetch(url)` then `setBlob`. Standard browser /
 *   worker entry point.
 *
 * Once loaded, `blob` is a `Uint8Array(122784)` and `isLoaded === true`.
 *
 * ## Wiring (browser)
 *
 * ```js
 * const dict  = runtime.resolve('brotliDict');
 * const words = runtime.resolve('brotliDictWords');
 *
 * // The .bin asset is served at the convention path under the importmap;
 * // override via your bundler / asset pipeline if you place it elsewhere.
 * await words.load('/packages/front/fw/src/io/compress/brotli_dict.bin');
 * dict.setWords(words.blob);
 * ```
 *
 * ## Wiring (Node / Bun)
 *
 * ```js
 * import fs from 'fs';
 * const bytes = new Uint8Array(fs.readFileSync('.../brotli_dict.bin'));
 * words.setBlob(bytes);
 * ```
 *
 * ## Vendored payload
 *
 * | Property | Value |
 * |----------|-------|
 * | Canonical spec | RFC 7932 Appendix A (hex dump of the `DICT` array) |
 * | Vendored from | https://raw.githubusercontent.com/google/brotli/master/c/common/dictionary.bin |
 * | Size | 122 784 bytes (RFC 7932 `DICTSIZE`) |
 * | CRC-32 (zlib polynomial) | `0x5136CB04` (also stated by Appendix A) |
 * | SHA-256 | `20e42eb1b511c21806d4d227d07e5dd06877d8ce7b3a817f378f313653f35c70` |
 *
 * The blob is **bit-identical** to the hexadecimal `DICT` array given in
 * RFC 7932 Appendix A. The current `brotli_dict.bin` is sourced from the
 * `google/brotli` reference repository for convenience, but the RFC text
 * itself is the authoritative source - `brotli_dict.bin` could equally be
 * regenerated by concatenating the hex lines of Appendix A and decoding
 * them, then verifying against `EXPECTED_SIZE` and `EXPECTED_CRC32`.
 *
 * Both `setBlob` and `load` validate size + CRC-32 before accepting the
 * blob; mismatches throw. All constants live **inside** the factory so
 * that `factory.toString()` produces a self-contained module string for
 * worker transport.
 *
 */

/**
 * Public surface of `brotliDictWords.factory()` (the mutable loader state).
 * @typedef {object} BrotliDictWordsAPI
 * @property {Uint8Array|null} blob The loaded 122784-byte dictionary, or `null` before loading.
 * @property {boolean} isLoaded `true` once a valid blob has been accepted.
 * @property {number} EXPECTED_SIZE Required blob size (122784).
 * @property {number} EXPECTED_CRC32 Required CRC-32 of the blob (0x5136CB04).
 * @property {(buf: Uint8Array) => Uint8Array} setBlob Validate (size + CRC-32) and accept a pre-loaded blob.
 * @property {(url: string) => Promise<Uint8Array>} load Fetch the blob from `url`, validate, and accept it.
 */

export const brotliDictWords = {
    name: 'brotliDictWords',
    version: '2.0.0',
    type: 'fw.io.compress',
    dependencies: [],

    /** @returns {BrotliDictWordsAPI} */
    factory() {

        // Expected decoded size, fixed by RFC 7932 (DICTSIZE).
        const EXPECTED_SIZE = 122784;

        // CRC-32 of the blob (zlib polynomial 0xEDB88320), verified against
        // the upstream google/brotli c/common/dictionary.bin.
        const EXPECTED_CRC32 = 0x5136CB04;

        const u8 = Uint8Array;

        // CRC-32 (zlib polynomial, RFC 1952 / RFC 7932 Appendix C). Inline
        // to keep this module dependency-free.
        function _crc32(buf) {
            let crc = 0xFFFFFFFF;
            for (let i = 0; i < buf.length; ++i) {
                let c = (crc ^ buf[i]) & 0xFF;
                for (let k = 0; k < 8; ++k) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
                crc = c ^ (crc >>> 8);
            }
            return (crc ^ 0xFFFFFFFF) >>> 0;
        }

        function _validate(buf) {
            if (!(buf instanceof u8)) {
                throw new Error('brotliDictWords: expected Uint8Array');
            }
            if (buf.length !== EXPECTED_SIZE) {
                throw new Error(
                    'brotliDictWords: size ' + buf.length + ' ≠ expected ' + EXPECTED_SIZE
                );
            }
            const got = _crc32(buf);
            if (got !== EXPECTED_CRC32) {
                throw new Error(
                    'brotliDictWords: CRC32 mismatch (got 0x' + got.toString(16) +
                    ', expected 0x' + EXPECTED_CRC32.toString(16) + ')'
                );
            }
        }

        const state = {
            blob: null,
            isLoaded: false,
            EXPECTED_SIZE,
            EXPECTED_CRC32,
        };

        function setBlob(buf) {
            _validate(buf);
            state.blob = buf;
            state.isLoaded = true;
            return buf;
        }

        async function load(url) {
            if (state.isLoaded) return state.blob;
            if (!url) throw new Error('brotliDictWords.load: url required');
            const r = await fetch(url);
            if (!r.ok) {
                throw new Error('brotliDictWords.load: HTTP ' + r.status + ' for ' + url);
            }
            const ab = await r.arrayBuffer();
            return setBlob(new u8(ab));
        }

        state.setBlob = setBlob;
        state.load = load;

        return /** @type {BrotliDictWordsAPI} */ (/** @type {any} */ (state));
    }
};
