// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: AGPL-3.0-only
// Dual-licensed; see the NOTICE file for licensing and any additional terms.

/**
 * @fileoverview Opt-in misc top-up: typed parse/render coverage for
 * residual SML elements (default-namespaced, no prefix) that don't fit
 * a dedicated sml-* phase module.
 *
 * @module ooxml/extra/sml-misc
 */

import { xml } from '@awacloud/fw/io/codec/xml.js';

export const smlMisc = {
    name: 'smlMisc',
    dependencies: ['xml'],
    deps: [xml],

    factory(xml) {
        const ELEMENTS = ["DataBinding","Map","MapInfo","Schema","anchor","autoSortScope","bk","bottom","cacheField","cacheHierarchies","cacheHierarchy","calcChain","calcPr","calculatedColumnFormula","calculatedItem","calculatedItems","calculatedMember","calculatedMembers","cell","cellMetadata","cellSmartTag","cellSmartTagPr","cellSmartTags","cellWatch","cellWatches","chartFormat","chartFormats","chartsheet","colBreaks","colFields","colHierarchiesUsage","colHierarchyUsage","colItems","colorFilter","colors","commentPr","condense","conditionalFormat","conditionalFormats","connection","connections","consolidation","control","controlPr","controls","customFilter","customFilters","customPr","customProperties","customSheetView","customSheetViews","customWorkbookView","d","dataConsolidate","dataField","dataFields","dataRef","dataRefs","dateGroupItem","dbPr","ddeItem","ddeItems","ddeLink","deletedField","diagonal","dialogsheet","dimensions","discretePr","drawingHF","dynamicFilter","e","end","entries","evenFooter","evenHeader","ext","extLst","extend","externalBook","externalLink","externalReference","externalReferences","field","fieldGroup","fieldUsage","fieldsUsage","fileRecoveryPr","fileSharing","fileVersion","filter","filterColumn","filters","firstFooter","firstHeader","format","formats","functionGroup","functionGroups","futureMetadata","group","header","headers","horizontal","iconFilter","ignoredError","ignoredErrors","indexedColors","inputCells","k","main","mdx","mdxMetadata","member","members","metadata","metadataStrings","metadataType","metadataTypes","mp","mpMap","mps","mruColors","ms","nc","ndxf","oc","odxf","olapPr","oldFormula","oleItem","oleItems","oleLink","outline","p","parameter","parameters","picture","pivotSelection","query","queryCache","queryTable","queryTableDeletedFields","queryTableField","queryTableFields","queryTableRefresh","rPh","raf","rc","rcc","rcft","rcmt","rcv","rdn","reviewed","reviewedList","revisions","rfmt","rgbColor","ris","rm","rqt","rrc","rsnm","scenario","scenarios","securityDescriptor","selection","serverFormat","serverFormats","set","sets","shadow","sheetDataSet","sheetId","sheetIdMap","sheetName","sheetNames","singleXmlCell","singleXmlCells","smartTags","sortByTuple","sortCondition","sortState","start","stop","stp","tableStyle","tableStyleElement","tables","textField","textFields","textPr","top","top10","totalsRowFormula","tp","tpl","tpls","tr","tupleCache","undo","userInfo","users","val","value","valueMetadata","values","vertical","volType","volTypes","webPr","webPublishItem","webPublishItems","workbookPr","xmlCellPr","xmlColumnPr","xmlPr"];

        function parseElement(el) {
            if (!el || el.type !== 'element') return null;
            switch (el.name) {
            case 'DataBinding': return { _passthrough: true, kind: 'DataBinding', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'Map': return { _passthrough: true, kind: 'Map', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'MapInfo': return { _passthrough: true, kind: 'MapInfo', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'Schema': return { _passthrough: true, kind: 'Schema', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'anchor': return { _passthrough: true, kind: 'anchor', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'autoSortScope': return { _passthrough: true, kind: 'autoSortScope', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'bk': return { _passthrough: true, kind: 'bk', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'bottom': return { _passthrough: true, kind: 'bottom', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cacheField': return { _passthrough: true, kind: 'cacheField', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cacheHierarchies': return { _passthrough: true, kind: 'cacheHierarchies', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cacheHierarchy': return { _passthrough: true, kind: 'cacheHierarchy', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'calcChain': return { _passthrough: true, kind: 'calcChain', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'calcPr': return { _passthrough: true, kind: 'calcPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'calculatedColumnFormula': return { _passthrough: true, kind: 'calculatedColumnFormula', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'calculatedItem': return { _passthrough: true, kind: 'calculatedItem', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'calculatedItems': return { _passthrough: true, kind: 'calculatedItems', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'calculatedMember': return { _passthrough: true, kind: 'calculatedMember', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'calculatedMembers': return { _passthrough: true, kind: 'calculatedMembers', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cell': return { _passthrough: true, kind: 'cell', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cellMetadata': return { _passthrough: true, kind: 'cellMetadata', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cellSmartTag': return { _passthrough: true, kind: 'cellSmartTag', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cellSmartTagPr': return { _passthrough: true, kind: 'cellSmartTagPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cellSmartTags': return { _passthrough: true, kind: 'cellSmartTags', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cellWatch': return { _passthrough: true, kind: 'cellWatch', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'cellWatches': return { _passthrough: true, kind: 'cellWatches', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'chartFormat': return { _passthrough: true, kind: 'chartFormat', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'chartFormats': return { _passthrough: true, kind: 'chartFormats', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'chartsheet': return { _passthrough: true, kind: 'chartsheet', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'colBreaks': return { _passthrough: true, kind: 'colBreaks', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'colFields': return { _passthrough: true, kind: 'colFields', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'colHierarchiesUsage': return { _passthrough: true, kind: 'colHierarchiesUsage', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'colHierarchyUsage': return { _passthrough: true, kind: 'colHierarchyUsage', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'colItems': return { _passthrough: true, kind: 'colItems', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'colorFilter': return { _passthrough: true, kind: 'colorFilter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'colors': return { _passthrough: true, kind: 'colors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'commentPr': return { _passthrough: true, kind: 'commentPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'condense': return { _passthrough: true, kind: 'condense', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'conditionalFormat': return { _passthrough: true, kind: 'conditionalFormat', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'conditionalFormats': return { _passthrough: true, kind: 'conditionalFormats', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'connection': return { _passthrough: true, kind: 'connection', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'connections': return { _passthrough: true, kind: 'connections', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'consolidation': return { _passthrough: true, kind: 'consolidation', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'control': return { _passthrough: true, kind: 'control', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'controlPr': return { _passthrough: true, kind: 'controlPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'controls': return { _passthrough: true, kind: 'controls', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'customFilter': return { _passthrough: true, kind: 'customFilter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'customFilters': return { _passthrough: true, kind: 'customFilters', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'customPr': return { _passthrough: true, kind: 'customPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'customProperties': return { _passthrough: true, kind: 'customProperties', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'customSheetView': return { _passthrough: true, kind: 'customSheetView', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'customSheetViews': return { _passthrough: true, kind: 'customSheetViews', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'customWorkbookView': return { _passthrough: true, kind: 'customWorkbookView', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'd': return { _passthrough: true, kind: 'd', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dataConsolidate': return { _passthrough: true, kind: 'dataConsolidate', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dataField': return { _passthrough: true, kind: 'dataField', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dataFields': return { _passthrough: true, kind: 'dataFields', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dataRef': return { _passthrough: true, kind: 'dataRef', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dataRefs': return { _passthrough: true, kind: 'dataRefs', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dateGroupItem': return { _passthrough: true, kind: 'dateGroupItem', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dbPr': return { _passthrough: true, kind: 'dbPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ddeItem': return { _passthrough: true, kind: 'ddeItem', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ddeItems': return { _passthrough: true, kind: 'ddeItems', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ddeLink': return { _passthrough: true, kind: 'ddeLink', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'deletedField': return { _passthrough: true, kind: 'deletedField', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'diagonal': return { _passthrough: true, kind: 'diagonal', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dialogsheet': return { _passthrough: true, kind: 'dialogsheet', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dimensions': return { _passthrough: true, kind: 'dimensions', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'discretePr': return { _passthrough: true, kind: 'discretePr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'drawingHF': return { _passthrough: true, kind: 'drawingHF', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'dynamicFilter': return { _passthrough: true, kind: 'dynamicFilter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'e': return { _passthrough: true, kind: 'e', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'end': return { _passthrough: true, kind: 'end', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'entries': return { _passthrough: true, kind: 'entries', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'evenFooter': return { _passthrough: true, kind: 'evenFooter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'evenHeader': return { _passthrough: true, kind: 'evenHeader', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ext': return { _passthrough: true, kind: 'ext', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'extLst': return { _passthrough: true, kind: 'extLst', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'extend': return { _passthrough: true, kind: 'extend', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'externalBook': return { _passthrough: true, kind: 'externalBook', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'externalLink': return { _passthrough: true, kind: 'externalLink', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'externalReference': return { _passthrough: true, kind: 'externalReference', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'externalReferences': return { _passthrough: true, kind: 'externalReferences', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'field': return { _passthrough: true, kind: 'field', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'fieldGroup': return { _passthrough: true, kind: 'fieldGroup', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'fieldUsage': return { _passthrough: true, kind: 'fieldUsage', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'fieldsUsage': return { _passthrough: true, kind: 'fieldsUsage', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'fileRecoveryPr': return { _passthrough: true, kind: 'fileRecoveryPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'fileSharing': return { _passthrough: true, kind: 'fileSharing', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'fileVersion': return { _passthrough: true, kind: 'fileVersion', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'filter': return { _passthrough: true, kind: 'filter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'filterColumn': return { _passthrough: true, kind: 'filterColumn', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'filters': return { _passthrough: true, kind: 'filters', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'firstFooter': return { _passthrough: true, kind: 'firstFooter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'firstHeader': return { _passthrough: true, kind: 'firstHeader', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'format': return { _passthrough: true, kind: 'format', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'formats': return { _passthrough: true, kind: 'formats', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'functionGroup': return { _passthrough: true, kind: 'functionGroup', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'functionGroups': return { _passthrough: true, kind: 'functionGroups', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'futureMetadata': return { _passthrough: true, kind: 'futureMetadata', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'group': return { _passthrough: true, kind: 'group', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'header': return { _passthrough: true, kind: 'header', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'headers': return { _passthrough: true, kind: 'headers', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'horizontal': return { _passthrough: true, kind: 'horizontal', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'iconFilter': return { _passthrough: true, kind: 'iconFilter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ignoredError': return { _passthrough: true, kind: 'ignoredError', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ignoredErrors': return { _passthrough: true, kind: 'ignoredErrors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'indexedColors': return { _passthrough: true, kind: 'indexedColors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'inputCells': return { _passthrough: true, kind: 'inputCells', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'k': return { _passthrough: true, kind: 'k', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'main': return { _passthrough: true, kind: 'main', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'mdx': return { _passthrough: true, kind: 'mdx', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'mdxMetadata': return { _passthrough: true, kind: 'mdxMetadata', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'member': return { _passthrough: true, kind: 'member', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'members': return { _passthrough: true, kind: 'members', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'metadata': return { _passthrough: true, kind: 'metadata', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'metadataStrings': return { _passthrough: true, kind: 'metadataStrings', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'metadataType': return { _passthrough: true, kind: 'metadataType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'metadataTypes': return { _passthrough: true, kind: 'metadataTypes', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'mp': return { _passthrough: true, kind: 'mp', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'mpMap': return { _passthrough: true, kind: 'mpMap', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'mps': return { _passthrough: true, kind: 'mps', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'mruColors': return { _passthrough: true, kind: 'mruColors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ms': return { _passthrough: true, kind: 'ms', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'nc': return { _passthrough: true, kind: 'nc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ndxf': return { _passthrough: true, kind: 'ndxf', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'oc': return { _passthrough: true, kind: 'oc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'odxf': return { _passthrough: true, kind: 'odxf', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'olapPr': return { _passthrough: true, kind: 'olapPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'oldFormula': return { _passthrough: true, kind: 'oldFormula', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'oleItem': return { _passthrough: true, kind: 'oleItem', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'oleItems': return { _passthrough: true, kind: 'oleItems', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'oleLink': return { _passthrough: true, kind: 'oleLink', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'outline': return { _passthrough: true, kind: 'outline', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'p': return { _passthrough: true, kind: 'p', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'parameter': return { _passthrough: true, kind: 'parameter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'parameters': return { _passthrough: true, kind: 'parameters', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'picture': return { _passthrough: true, kind: 'picture', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'pivotSelection': return { _passthrough: true, kind: 'pivotSelection', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'query': return { _passthrough: true, kind: 'query', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'queryCache': return { _passthrough: true, kind: 'queryCache', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'queryTable': return { _passthrough: true, kind: 'queryTable', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'queryTableDeletedFields': return { _passthrough: true, kind: 'queryTableDeletedFields', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'queryTableField': return { _passthrough: true, kind: 'queryTableField', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'queryTableFields': return { _passthrough: true, kind: 'queryTableFields', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'queryTableRefresh': return { _passthrough: true, kind: 'queryTableRefresh', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rPh': return { _passthrough: true, kind: 'rPh', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'raf': return { _passthrough: true, kind: 'raf', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rc': return { _passthrough: true, kind: 'rc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rcc': return { _passthrough: true, kind: 'rcc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rcft': return { _passthrough: true, kind: 'rcft', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rcmt': return { _passthrough: true, kind: 'rcmt', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rcv': return { _passthrough: true, kind: 'rcv', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rdn': return { _passthrough: true, kind: 'rdn', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'reviewed': return { _passthrough: true, kind: 'reviewed', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'reviewedList': return { _passthrough: true, kind: 'reviewedList', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'revisions': return { _passthrough: true, kind: 'revisions', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rfmt': return { _passthrough: true, kind: 'rfmt', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rgbColor': return { _passthrough: true, kind: 'rgbColor', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'ris': return { _passthrough: true, kind: 'ris', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rm': return { _passthrough: true, kind: 'rm', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rqt': return { _passthrough: true, kind: 'rqt', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rrc': return { _passthrough: true, kind: 'rrc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'rsnm': return { _passthrough: true, kind: 'rsnm', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'scenario': return { _passthrough: true, kind: 'scenario', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'scenarios': return { _passthrough: true, kind: 'scenarios', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'securityDescriptor': return { _passthrough: true, kind: 'securityDescriptor', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'selection': return { _passthrough: true, kind: 'selection', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'serverFormat': return { _passthrough: true, kind: 'serverFormat', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'serverFormats': return { _passthrough: true, kind: 'serverFormats', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'set': return { _passthrough: true, kind: 'set', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sets': return { _passthrough: true, kind: 'sets', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'shadow': return { _passthrough: true, kind: 'shadow', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sheetDataSet': return { _passthrough: true, kind: 'sheetDataSet', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sheetId': return { _passthrough: true, kind: 'sheetId', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sheetIdMap': return { _passthrough: true, kind: 'sheetIdMap', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sheetName': return { _passthrough: true, kind: 'sheetName', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sheetNames': return { _passthrough: true, kind: 'sheetNames', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'singleXmlCell': return { _passthrough: true, kind: 'singleXmlCell', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'singleXmlCells': return { _passthrough: true, kind: 'singleXmlCells', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'smartTags': return { _passthrough: true, kind: 'smartTags', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sortByTuple': return { _passthrough: true, kind: 'sortByTuple', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sortCondition': return { _passthrough: true, kind: 'sortCondition', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'sortState': return { _passthrough: true, kind: 'sortState', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'start': return { _passthrough: true, kind: 'start', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'stop': return { _passthrough: true, kind: 'stop', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'stp': return { _passthrough: true, kind: 'stp', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tableStyle': return { _passthrough: true, kind: 'tableStyle', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tableStyleElement': return { _passthrough: true, kind: 'tableStyleElement', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tables': return { _passthrough: true, kind: 'tables', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'textField': return { _passthrough: true, kind: 'textField', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'textFields': return { _passthrough: true, kind: 'textFields', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'textPr': return { _passthrough: true, kind: 'textPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'top': return { _passthrough: true, kind: 'top', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'top10': return { _passthrough: true, kind: 'top10', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'totalsRowFormula': return { _passthrough: true, kind: 'totalsRowFormula', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tp': return { _passthrough: true, kind: 'tp', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tpl': return { _passthrough: true, kind: 'tpl', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tpls': return { _passthrough: true, kind: 'tpls', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tr': return { _passthrough: true, kind: 'tr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'tupleCache': return { _passthrough: true, kind: 'tupleCache', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'undo': return { _passthrough: true, kind: 'undo', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'userInfo': return { _passthrough: true, kind: 'userInfo', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'users': return { _passthrough: true, kind: 'users', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'val': return { _passthrough: true, kind: 'val', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'value': return { _passthrough: true, kind: 'value', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'valueMetadata': return { _passthrough: true, kind: 'valueMetadata', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'values': return { _passthrough: true, kind: 'values', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'vertical': return { _passthrough: true, kind: 'vertical', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'volType': return { _passthrough: true, kind: 'volType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'volTypes': return { _passthrough: true, kind: 'volTypes', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'webPr': return { _passthrough: true, kind: 'webPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'webPublishItem': return { _passthrough: true, kind: 'webPublishItem', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'webPublishItems': return { _passthrough: true, kind: 'webPublishItems', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'workbookPr': return { _passthrough: true, kind: 'workbookPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'xmlCellPr': return { _passthrough: true, kind: 'xmlCellPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'xmlColumnPr': return { _passthrough: true, kind: 'xmlColumnPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'xmlPr': return { _passthrough: true, kind: 'xmlPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
                default: return null;
            }
        }

        function renderElement(obj) {
            if (!obj || !obj.kind) return null;
            switch (obj.kind) {
            case 'DataBinding': return xml.el('DataBinding', obj.attrs || {}, obj.children || []);
            case 'Map': return xml.el('Map', obj.attrs || {}, obj.children || []);
            case 'MapInfo': return xml.el('MapInfo', obj.attrs || {}, obj.children || []);
            case 'Schema': return xml.el('Schema', obj.attrs || {}, obj.children || []);
            case 'anchor': return xml.el('anchor', obj.attrs || {}, obj.children || []);
            case 'autoSortScope': return xml.el('autoSortScope', obj.attrs || {}, obj.children || []);
            case 'bk': return xml.el('bk', obj.attrs || {}, obj.children || []);
            case 'bottom': return xml.el('bottom', obj.attrs || {}, obj.children || []);
            case 'cacheField': return xml.el('cacheField', obj.attrs || {}, obj.children || []);
            case 'cacheHierarchies': return xml.el('cacheHierarchies', obj.attrs || {}, obj.children || []);
            case 'cacheHierarchy': return xml.el('cacheHierarchy', obj.attrs || {}, obj.children || []);
            case 'calcChain': return xml.el('calcChain', obj.attrs || {}, obj.children || []);
            case 'calcPr': return xml.el('calcPr', obj.attrs || {}, obj.children || []);
            case 'calculatedColumnFormula': return xml.el('calculatedColumnFormula', obj.attrs || {}, obj.children || []);
            case 'calculatedItem': return xml.el('calculatedItem', obj.attrs || {}, obj.children || []);
            case 'calculatedItems': return xml.el('calculatedItems', obj.attrs || {}, obj.children || []);
            case 'calculatedMember': return xml.el('calculatedMember', obj.attrs || {}, obj.children || []);
            case 'calculatedMembers': return xml.el('calculatedMembers', obj.attrs || {}, obj.children || []);
            case 'cell': return xml.el('cell', obj.attrs || {}, obj.children || []);
            case 'cellMetadata': return xml.el('cellMetadata', obj.attrs || {}, obj.children || []);
            case 'cellSmartTag': return xml.el('cellSmartTag', obj.attrs || {}, obj.children || []);
            case 'cellSmartTagPr': return xml.el('cellSmartTagPr', obj.attrs || {}, obj.children || []);
            case 'cellSmartTags': return xml.el('cellSmartTags', obj.attrs || {}, obj.children || []);
            case 'cellWatch': return xml.el('cellWatch', obj.attrs || {}, obj.children || []);
            case 'cellWatches': return xml.el('cellWatches', obj.attrs || {}, obj.children || []);
            case 'chartFormat': return xml.el('chartFormat', obj.attrs || {}, obj.children || []);
            case 'chartFormats': return xml.el('chartFormats', obj.attrs || {}, obj.children || []);
            case 'chartsheet': return xml.el('chartsheet', obj.attrs || {}, obj.children || []);
            case 'colBreaks': return xml.el('colBreaks', obj.attrs || {}, obj.children || []);
            case 'colFields': return xml.el('colFields', obj.attrs || {}, obj.children || []);
            case 'colHierarchiesUsage': return xml.el('colHierarchiesUsage', obj.attrs || {}, obj.children || []);
            case 'colHierarchyUsage': return xml.el('colHierarchyUsage', obj.attrs || {}, obj.children || []);
            case 'colItems': return xml.el('colItems', obj.attrs || {}, obj.children || []);
            case 'colorFilter': return xml.el('colorFilter', obj.attrs || {}, obj.children || []);
            case 'colors': return xml.el('colors', obj.attrs || {}, obj.children || []);
            case 'commentPr': return xml.el('commentPr', obj.attrs || {}, obj.children || []);
            case 'condense': return xml.el('condense', obj.attrs || {}, obj.children || []);
            case 'conditionalFormat': return xml.el('conditionalFormat', obj.attrs || {}, obj.children || []);
            case 'conditionalFormats': return xml.el('conditionalFormats', obj.attrs || {}, obj.children || []);
            case 'connection': return xml.el('connection', obj.attrs || {}, obj.children || []);
            case 'connections': return xml.el('connections', obj.attrs || {}, obj.children || []);
            case 'consolidation': return xml.el('consolidation', obj.attrs || {}, obj.children || []);
            case 'control': return xml.el('control', obj.attrs || {}, obj.children || []);
            case 'controlPr': return xml.el('controlPr', obj.attrs || {}, obj.children || []);
            case 'controls': return xml.el('controls', obj.attrs || {}, obj.children || []);
            case 'customFilter': return xml.el('customFilter', obj.attrs || {}, obj.children || []);
            case 'customFilters': return xml.el('customFilters', obj.attrs || {}, obj.children || []);
            case 'customPr': return xml.el('customPr', obj.attrs || {}, obj.children || []);
            case 'customProperties': return xml.el('customProperties', obj.attrs || {}, obj.children || []);
            case 'customSheetView': return xml.el('customSheetView', obj.attrs || {}, obj.children || []);
            case 'customSheetViews': return xml.el('customSheetViews', obj.attrs || {}, obj.children || []);
            case 'customWorkbookView': return xml.el('customWorkbookView', obj.attrs || {}, obj.children || []);
            case 'd': return xml.el('d', obj.attrs || {}, obj.children || []);
            case 'dataConsolidate': return xml.el('dataConsolidate', obj.attrs || {}, obj.children || []);
            case 'dataField': return xml.el('dataField', obj.attrs || {}, obj.children || []);
            case 'dataFields': return xml.el('dataFields', obj.attrs || {}, obj.children || []);
            case 'dataRef': return xml.el('dataRef', obj.attrs || {}, obj.children || []);
            case 'dataRefs': return xml.el('dataRefs', obj.attrs || {}, obj.children || []);
            case 'dateGroupItem': return xml.el('dateGroupItem', obj.attrs || {}, obj.children || []);
            case 'dbPr': return xml.el('dbPr', obj.attrs || {}, obj.children || []);
            case 'ddeItem': return xml.el('ddeItem', obj.attrs || {}, obj.children || []);
            case 'ddeItems': return xml.el('ddeItems', obj.attrs || {}, obj.children || []);
            case 'ddeLink': return xml.el('ddeLink', obj.attrs || {}, obj.children || []);
            case 'deletedField': return xml.el('deletedField', obj.attrs || {}, obj.children || []);
            case 'diagonal': return xml.el('diagonal', obj.attrs || {}, obj.children || []);
            case 'dialogsheet': return xml.el('dialogsheet', obj.attrs || {}, obj.children || []);
            case 'dimensions': return xml.el('dimensions', obj.attrs || {}, obj.children || []);
            case 'discretePr': return xml.el('discretePr', obj.attrs || {}, obj.children || []);
            case 'drawingHF': return xml.el('drawingHF', obj.attrs || {}, obj.children || []);
            case 'dynamicFilter': return xml.el('dynamicFilter', obj.attrs || {}, obj.children || []);
            case 'e': return xml.el('e', obj.attrs || {}, obj.children || []);
            case 'end': return xml.el('end', obj.attrs || {}, obj.children || []);
            case 'entries': return xml.el('entries', obj.attrs || {}, obj.children || []);
            case 'evenFooter': return xml.el('evenFooter', obj.attrs || {}, obj.children || []);
            case 'evenHeader': return xml.el('evenHeader', obj.attrs || {}, obj.children || []);
            case 'ext': return xml.el('ext', obj.attrs || {}, obj.children || []);
            case 'extLst': return xml.el('extLst', obj.attrs || {}, obj.children || []);
            case 'extend': return xml.el('extend', obj.attrs || {}, obj.children || []);
            case 'externalBook': return xml.el('externalBook', obj.attrs || {}, obj.children || []);
            case 'externalLink': return xml.el('externalLink', obj.attrs || {}, obj.children || []);
            case 'externalReference': return xml.el('externalReference', obj.attrs || {}, obj.children || []);
            case 'externalReferences': return xml.el('externalReferences', obj.attrs || {}, obj.children || []);
            case 'field': return xml.el('field', obj.attrs || {}, obj.children || []);
            case 'fieldGroup': return xml.el('fieldGroup', obj.attrs || {}, obj.children || []);
            case 'fieldUsage': return xml.el('fieldUsage', obj.attrs || {}, obj.children || []);
            case 'fieldsUsage': return xml.el('fieldsUsage', obj.attrs || {}, obj.children || []);
            case 'fileRecoveryPr': return xml.el('fileRecoveryPr', obj.attrs || {}, obj.children || []);
            case 'fileSharing': return xml.el('fileSharing', obj.attrs || {}, obj.children || []);
            case 'fileVersion': return xml.el('fileVersion', obj.attrs || {}, obj.children || []);
            case 'filter': return xml.el('filter', obj.attrs || {}, obj.children || []);
            case 'filterColumn': return xml.el('filterColumn', obj.attrs || {}, obj.children || []);
            case 'filters': return xml.el('filters', obj.attrs || {}, obj.children || []);
            case 'firstFooter': return xml.el('firstFooter', obj.attrs || {}, obj.children || []);
            case 'firstHeader': return xml.el('firstHeader', obj.attrs || {}, obj.children || []);
            case 'format': return xml.el('format', obj.attrs || {}, obj.children || []);
            case 'formats': return xml.el('formats', obj.attrs || {}, obj.children || []);
            case 'functionGroup': return xml.el('functionGroup', obj.attrs || {}, obj.children || []);
            case 'functionGroups': return xml.el('functionGroups', obj.attrs || {}, obj.children || []);
            case 'futureMetadata': return xml.el('futureMetadata', obj.attrs || {}, obj.children || []);
            case 'group': return xml.el('group', obj.attrs || {}, obj.children || []);
            case 'header': return xml.el('header', obj.attrs || {}, obj.children || []);
            case 'headers': return xml.el('headers', obj.attrs || {}, obj.children || []);
            case 'horizontal': return xml.el('horizontal', obj.attrs || {}, obj.children || []);
            case 'iconFilter': return xml.el('iconFilter', obj.attrs || {}, obj.children || []);
            case 'ignoredError': return xml.el('ignoredError', obj.attrs || {}, obj.children || []);
            case 'ignoredErrors': return xml.el('ignoredErrors', obj.attrs || {}, obj.children || []);
            case 'indexedColors': return xml.el('indexedColors', obj.attrs || {}, obj.children || []);
            case 'inputCells': return xml.el('inputCells', obj.attrs || {}, obj.children || []);
            case 'k': return xml.el('k', obj.attrs || {}, obj.children || []);
            case 'main': return xml.el('main', obj.attrs || {}, obj.children || []);
            case 'mdx': return xml.el('mdx', obj.attrs || {}, obj.children || []);
            case 'mdxMetadata': return xml.el('mdxMetadata', obj.attrs || {}, obj.children || []);
            case 'member': return xml.el('member', obj.attrs || {}, obj.children || []);
            case 'members': return xml.el('members', obj.attrs || {}, obj.children || []);
            case 'metadata': return xml.el('metadata', obj.attrs || {}, obj.children || []);
            case 'metadataStrings': return xml.el('metadataStrings', obj.attrs || {}, obj.children || []);
            case 'metadataType': return xml.el('metadataType', obj.attrs || {}, obj.children || []);
            case 'metadataTypes': return xml.el('metadataTypes', obj.attrs || {}, obj.children || []);
            case 'mp': return xml.el('mp', obj.attrs || {}, obj.children || []);
            case 'mpMap': return xml.el('mpMap', obj.attrs || {}, obj.children || []);
            case 'mps': return xml.el('mps', obj.attrs || {}, obj.children || []);
            case 'mruColors': return xml.el('mruColors', obj.attrs || {}, obj.children || []);
            case 'ms': return xml.el('ms', obj.attrs || {}, obj.children || []);
            case 'nc': return xml.el('nc', obj.attrs || {}, obj.children || []);
            case 'ndxf': return xml.el('ndxf', obj.attrs || {}, obj.children || []);
            case 'oc': return xml.el('oc', obj.attrs || {}, obj.children || []);
            case 'odxf': return xml.el('odxf', obj.attrs || {}, obj.children || []);
            case 'olapPr': return xml.el('olapPr', obj.attrs || {}, obj.children || []);
            case 'oldFormula': return xml.el('oldFormula', obj.attrs || {}, obj.children || []);
            case 'oleItem': return xml.el('oleItem', obj.attrs || {}, obj.children || []);
            case 'oleItems': return xml.el('oleItems', obj.attrs || {}, obj.children || []);
            case 'oleLink': return xml.el('oleLink', obj.attrs || {}, obj.children || []);
            case 'outline': return xml.el('outline', obj.attrs || {}, obj.children || []);
            case 'p': return xml.el('p', obj.attrs || {}, obj.children || []);
            case 'parameter': return xml.el('parameter', obj.attrs || {}, obj.children || []);
            case 'parameters': return xml.el('parameters', obj.attrs || {}, obj.children || []);
            case 'picture': return xml.el('picture', obj.attrs || {}, obj.children || []);
            case 'pivotSelection': return xml.el('pivotSelection', obj.attrs || {}, obj.children || []);
            case 'query': return xml.el('query', obj.attrs || {}, obj.children || []);
            case 'queryCache': return xml.el('queryCache', obj.attrs || {}, obj.children || []);
            case 'queryTable': return xml.el('queryTable', obj.attrs || {}, obj.children || []);
            case 'queryTableDeletedFields': return xml.el('queryTableDeletedFields', obj.attrs || {}, obj.children || []);
            case 'queryTableField': return xml.el('queryTableField', obj.attrs || {}, obj.children || []);
            case 'queryTableFields': return xml.el('queryTableFields', obj.attrs || {}, obj.children || []);
            case 'queryTableRefresh': return xml.el('queryTableRefresh', obj.attrs || {}, obj.children || []);
            case 'rPh': return xml.el('rPh', obj.attrs || {}, obj.children || []);
            case 'raf': return xml.el('raf', obj.attrs || {}, obj.children || []);
            case 'rc': return xml.el('rc', obj.attrs || {}, obj.children || []);
            case 'rcc': return xml.el('rcc', obj.attrs || {}, obj.children || []);
            case 'rcft': return xml.el('rcft', obj.attrs || {}, obj.children || []);
            case 'rcmt': return xml.el('rcmt', obj.attrs || {}, obj.children || []);
            case 'rcv': return xml.el('rcv', obj.attrs || {}, obj.children || []);
            case 'rdn': return xml.el('rdn', obj.attrs || {}, obj.children || []);
            case 'reviewed': return xml.el('reviewed', obj.attrs || {}, obj.children || []);
            case 'reviewedList': return xml.el('reviewedList', obj.attrs || {}, obj.children || []);
            case 'revisions': return xml.el('revisions', obj.attrs || {}, obj.children || []);
            case 'rfmt': return xml.el('rfmt', obj.attrs || {}, obj.children || []);
            case 'rgbColor': return xml.el('rgbColor', obj.attrs || {}, obj.children || []);
            case 'ris': return xml.el('ris', obj.attrs || {}, obj.children || []);
            case 'rm': return xml.el('rm', obj.attrs || {}, obj.children || []);
            case 'rqt': return xml.el('rqt', obj.attrs || {}, obj.children || []);
            case 'rrc': return xml.el('rrc', obj.attrs || {}, obj.children || []);
            case 'rsnm': return xml.el('rsnm', obj.attrs || {}, obj.children || []);
            case 'scenario': return xml.el('scenario', obj.attrs || {}, obj.children || []);
            case 'scenarios': return xml.el('scenarios', obj.attrs || {}, obj.children || []);
            case 'securityDescriptor': return xml.el('securityDescriptor', obj.attrs || {}, obj.children || []);
            case 'selection': return xml.el('selection', obj.attrs || {}, obj.children || []);
            case 'serverFormat': return xml.el('serverFormat', obj.attrs || {}, obj.children || []);
            case 'serverFormats': return xml.el('serverFormats', obj.attrs || {}, obj.children || []);
            case 'set': return xml.el('set', obj.attrs || {}, obj.children || []);
            case 'sets': return xml.el('sets', obj.attrs || {}, obj.children || []);
            case 'shadow': return xml.el('shadow', obj.attrs || {}, obj.children || []);
            case 'sheetDataSet': return xml.el('sheetDataSet', obj.attrs || {}, obj.children || []);
            case 'sheetId': return xml.el('sheetId', obj.attrs || {}, obj.children || []);
            case 'sheetIdMap': return xml.el('sheetIdMap', obj.attrs || {}, obj.children || []);
            case 'sheetName': return xml.el('sheetName', obj.attrs || {}, obj.children || []);
            case 'sheetNames': return xml.el('sheetNames', obj.attrs || {}, obj.children || []);
            case 'singleXmlCell': return xml.el('singleXmlCell', obj.attrs || {}, obj.children || []);
            case 'singleXmlCells': return xml.el('singleXmlCells', obj.attrs || {}, obj.children || []);
            case 'smartTags': return xml.el('smartTags', obj.attrs || {}, obj.children || []);
            case 'sortByTuple': return xml.el('sortByTuple', obj.attrs || {}, obj.children || []);
            case 'sortCondition': return xml.el('sortCondition', obj.attrs || {}, obj.children || []);
            case 'sortState': return xml.el('sortState', obj.attrs || {}, obj.children || []);
            case 'start': return xml.el('start', obj.attrs || {}, obj.children || []);
            case 'stop': return xml.el('stop', obj.attrs || {}, obj.children || []);
            case 'stp': return xml.el('stp', obj.attrs || {}, obj.children || []);
            case 'tableStyle': return xml.el('tableStyle', obj.attrs || {}, obj.children || []);
            case 'tableStyleElement': return xml.el('tableStyleElement', obj.attrs || {}, obj.children || []);
            case 'tables': return xml.el('tables', obj.attrs || {}, obj.children || []);
            case 'textField': return xml.el('textField', obj.attrs || {}, obj.children || []);
            case 'textFields': return xml.el('textFields', obj.attrs || {}, obj.children || []);
            case 'textPr': return xml.el('textPr', obj.attrs || {}, obj.children || []);
            case 'top': return xml.el('top', obj.attrs || {}, obj.children || []);
            case 'top10': return xml.el('top10', obj.attrs || {}, obj.children || []);
            case 'totalsRowFormula': return xml.el('totalsRowFormula', obj.attrs || {}, obj.children || []);
            case 'tp': return xml.el('tp', obj.attrs || {}, obj.children || []);
            case 'tpl': return xml.el('tpl', obj.attrs || {}, obj.children || []);
            case 'tpls': return xml.el('tpls', obj.attrs || {}, obj.children || []);
            case 'tr': return xml.el('tr', obj.attrs || {}, obj.children || []);
            case 'tupleCache': return xml.el('tupleCache', obj.attrs || {}, obj.children || []);
            case 'undo': return xml.el('undo', obj.attrs || {}, obj.children || []);
            case 'userInfo': return xml.el('userInfo', obj.attrs || {}, obj.children || []);
            case 'users': return xml.el('users', obj.attrs || {}, obj.children || []);
            case 'val': return xml.el('val', obj.attrs || {}, obj.children || []);
            case 'value': return xml.el('value', obj.attrs || {}, obj.children || []);
            case 'valueMetadata': return xml.el('valueMetadata', obj.attrs || {}, obj.children || []);
            case 'values': return xml.el('values', obj.attrs || {}, obj.children || []);
            case 'vertical': return xml.el('vertical', obj.attrs || {}, obj.children || []);
            case 'volType': return xml.el('volType', obj.attrs || {}, obj.children || []);
            case 'volTypes': return xml.el('volTypes', obj.attrs || {}, obj.children || []);
            case 'webPr': return xml.el('webPr', obj.attrs || {}, obj.children || []);
            case 'webPublishItem': return xml.el('webPublishItem', obj.attrs || {}, obj.children || []);
            case 'webPublishItems': return xml.el('webPublishItems', obj.attrs || {}, obj.children || []);
            case 'workbookPr': return xml.el('workbookPr', obj.attrs || {}, obj.children || []);
            case 'xmlCellPr': return xml.el('xmlCellPr', obj.attrs || {}, obj.children || []);
            case 'xmlColumnPr': return xml.el('xmlColumnPr', obj.attrs || {}, obj.children || []);
            case 'xmlPr': return xml.el('xmlPr', obj.attrs || {}, obj.children || []);
                default: return null;
            }
        }

        return { parseElement, renderElement, ELEMENTS };
    }
};
