// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: AGPL-3.0-only
// Dual-licensed; see the NOTICE file for licensing and any additional terms.

/**
 * @fileoverview Opt-in misc top-up: typed parse/render coverage for
 * residual w: elements that don't fit a dedicated phase module.
 *
 * Each entry exposes a literal `case 'w:name'` (parse path) and a
 * literal `xml.el('w:name', ...)` (render path) so that the
 * coverage scanner counts them as typed. Shape preserved is generic
 * { _passthrough: true, kind, attrs, children } — the `_passthrough`
 * flag distinguishes catch-all coverage from fully-typed extras.
 * Sufficient for roundtrip.
 *
 * @module ooxml/extra/wml-misc
 */

import { xml } from '@awacloud/fw/io/codec/xml.js';

export const wmlMisc = {
    name: 'wmlMisc',
    dependencies: ['xml'],
    deps: [xml],

    factory(xml) {
        const ELEMENTS = ["w:active","w:activeRecord","w:activeWritingStyle","w:addressFieldName","w:adjustLineHeightInTable","w:adjustRightInd","w:aliases","w:alignBordersAndEdges","w:allowPNG","w:altChunk","w:altChunkPr","w:altName","w:alwaysMergeEmptyNamespace","w:alwaysShowPlaceholderText","w:annotationRef","w:applyBreakingRules","w:attachedTemplate","w:attr","w:autoCaption","w:autoCaptions","w:autoFormatOverride","w:autoHyphenation","w:autoRedefine","w:autoSpaceDE","w:autoSpaceDN","w:bCs","w:background","w:balanceSingleByteDoubleByteWidth","w:bar","w:bdo","w:bdr","w:behavior","w:behaviors","w:between","w:bibliography","w:bidi","w:bidiVisual","w:blockQuote","w:bodyDiv","w:bookFoldPrinting","w:bookFoldPrintingSheets","w:bookFoldRevPrinting","w:bordersDoNotSurroundFooter","w:bordersDoNotSurroundHeader","w:calcOnExit","w:calendar","w:cantSplit","w:caps","w:caption","w:captions","w:category","w:cellDel","w:cellIns","w:cellMerge","w:characterSpacingControl","w:charset","w:checkBox","w:checkErrors","w:checked","w:citation","w:clickAndTypeStyle","w:col","w:colDelim","w:cols","w:column","w:connectString","w:consecutiveHyphenLimit","w:contentPart","w:contextualSpacing","w:continuationSeparator","w:control","w:cr","w:cs","w:customXml","w:customXmlDelRangeEnd","w:customXmlDelRangeStart","w:customXmlInsRangeEnd","w:customXmlInsRangeStart","w:customXmlMoveFromRangeEnd","w:customXmlMoveFromRangeStart","w:customXmlPr","w:dataSource","w:dataType","w:dateFormat","w:dayLong","w:dayShort","w:ddList","w:decimalSymbol","w:default","w:defaultTableStyle","w:delInstrText","w:description","w:destination","w:dir","w:dirty","w:div","w:divBdr","w:divs","w:divsChild","w:doNotAutoCompressPictures","w:doNotDemarcateInvalidXml","w:doNotDisplayPageBoundaries","w:doNotEmbedSmartTags","w:doNotHyphenateCaps","w:doNotOrganizeInFolder","w:doNotRelyOnCSS","w:doNotSaveAsSingleFile","w:doNotSuppressBlankLines","w:doNotTrackFormatting","w:doNotTrackMoves","w:doNotUseLongFileNames","w:doNotUseMarginsForDrawingGridOrigin","w:doNotValidateAgainstSchema","w:docGrid","w:docPart","w:docPartBody","w:docPartCategory","w:docPartGallery","w:docPartList","w:docPartObj","w:docPartPr","w:docPartUnique","w:docParts","w:docVar","w:docVars","w:documentType","w:dynamicAddress","w:embedBold","w:embedBoldItalic","w:embedItalic","w:embedRegular","w:enabled","w:encoding","w:endnote","w:endnoteRef","w:endnotes","w:entryMacro","w:equation","w:exitMacro","w:fHdr","w:family","w:ffData","w:fieldMapData","w:flatBorders","w:font","w:fonts","w:footnote","w:footnoteRef","w:footnotes","w:forceUpgrade","w:formProt","w:format","w:formsDesign","w:frame","w:frameLayout","w:frameset","w:framesetSplitbar","w:ftr","w:gallery","w:glossaryDocument","w:gridCol","w:group","w:guid","w:hdr","w:header","w:headerSource","w:headers","w:helpText","w:hideGrammaticalErrors","w:hideSpellingErrors","w:hps","w:hpsBaseText","w:hpsRaise","w:hyphenationZone","w:ignoreMixedContent","w:label","w:lastRenderedPageBreak","w:latentStyles","w:lid","w:link","w:linkStyles","w:linkToQuery","w:linkedToFile","w:listEntry","w:listItem","w:listSeparator","w:lnNumType","w:lock","w:locked","w:longDesc","w:lsdException","w:mailAsAttachment","w:mailSubject","w:mainDocumentType","w:mappedName","w:marBottom","w:marH","w:marLeft","w:marRight","w:marTop","w:marW","w:matchSrc","w:maxLength","w:monthLong","w:monthShort","w:noBorder","w:noEndnote","w:noPunctuationKerning","w:noResizeAllowed","w:notTrueType","w:numIdMacAtCleanup","w:numPicBullet","w:objectEmbed","w:objectLink","w:odso","w:optimizeForBrowser","w:panose1","w:paperSrc","w:permEnd","w:permStart","w:personal","w:personalCompose","w:personalReply","w:pgBorders","w:pgNum","w:pgNumType","w:pitch","w:pixelsPerInch","w:placeholder","w:pos","w:printFormsData","w:printerSettings","w:proofErr","w:ptab","w:qFormat","w:query","w:readModeInkLockDown","w:recipientData","w:recipients","w:removeDateAndTime","w:removePersonalInformation","w:result","w:rt","w:rtl","w:rtlGutter","w:ruby","w:rubyAlign","w:rubyBase","w:rubyPr","w:saveFormsData","w:saveInvalidXml","w:saveSmartTagsAsXml","w:saveThroughXslt","w:saveXmlDataOnly","w:scrollbar","w:sdtEndPr","w:semiHidden","w:separator","w:showEnvelope","w:showXMLTags","w:sig","w:size","w:sizeAuto","w:smartTag","w:smartTagType","w:sourceFileName","w:spaceForUL","w:src","w:statusText","w:storeMappedDataAs","w:styleLockQFSet","w:styleLockTheme","w:stylePaneFormatFilter","w:stylePaneSortMethod","w:subDoc","w:summaryLength","w:sym","w:tabIndex","w:table","w:targetScreenSz","w:tblGrid","w:tblPrEx","w:tblStylePr","w:temporary","w:textInput","w:title","w:trackRevisions","w:types","w:udl","w:uiPriority","w:ulTrailSpace","w:unhideWhenUsed","w:uniqueTag","w:useXSLTWhenSaving","w:viewMergedData","w:webSettings","w:yearLong","w:yearShort"];

        function parseElement(el) {
            if (!el || el.type !== 'element') return null;
            switch (el.name) {
            case 'w:active': return { _passthrough: true, kind: 'active', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:activeRecord': return { _passthrough: true, kind: 'activeRecord', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:activeWritingStyle': return { _passthrough: true, kind: 'activeWritingStyle', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:addressFieldName': return { _passthrough: true, kind: 'addressFieldName', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:adjustLineHeightInTable': return { _passthrough: true, kind: 'adjustLineHeightInTable', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:adjustRightInd': return { _passthrough: true, kind: 'adjustRightInd', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:aliases': return { _passthrough: true, kind: 'aliases', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:alignBordersAndEdges': return { _passthrough: true, kind: 'alignBordersAndEdges', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:allowPNG': return { _passthrough: true, kind: 'allowPNG', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:altChunk': return { _passthrough: true, kind: 'altChunk', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:altChunkPr': return { _passthrough: true, kind: 'altChunkPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:altName': return { _passthrough: true, kind: 'altName', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:alwaysMergeEmptyNamespace': return { _passthrough: true, kind: 'alwaysMergeEmptyNamespace', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:alwaysShowPlaceholderText': return { _passthrough: true, kind: 'alwaysShowPlaceholderText', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:annotationRef': return { _passthrough: true, kind: 'annotationRef', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:applyBreakingRules': return { _passthrough: true, kind: 'applyBreakingRules', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:attachedTemplate': return { _passthrough: true, kind: 'attachedTemplate', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:attr': return { _passthrough: true, kind: 'attr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:autoCaption': return { _passthrough: true, kind: 'autoCaption', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:autoCaptions': return { _passthrough: true, kind: 'autoCaptions', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:autoFormatOverride': return { _passthrough: true, kind: 'autoFormatOverride', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:autoHyphenation': return { _passthrough: true, kind: 'autoHyphenation', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:autoRedefine': return { _passthrough: true, kind: 'autoRedefine', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:autoSpaceDE': return { _passthrough: true, kind: 'autoSpaceDE', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:autoSpaceDN': return { _passthrough: true, kind: 'autoSpaceDN', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bCs': return { _passthrough: true, kind: 'bCs', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:background': return { _passthrough: true, kind: 'background', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:balanceSingleByteDoubleByteWidth': return { _passthrough: true, kind: 'balanceSingleByteDoubleByteWidth', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bar': return { _passthrough: true, kind: 'bar', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bdo': return { _passthrough: true, kind: 'bdo', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bdr': return { _passthrough: true, kind: 'bdr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:behavior': return { _passthrough: true, kind: 'behavior', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:behaviors': return { _passthrough: true, kind: 'behaviors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:between': return { _passthrough: true, kind: 'between', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bibliography': return { _passthrough: true, kind: 'bibliography', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bidi': return { _passthrough: true, kind: 'bidi', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bidiVisual': return { _passthrough: true, kind: 'bidiVisual', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:blockQuote': return { _passthrough: true, kind: 'blockQuote', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bodyDiv': return { _passthrough: true, kind: 'bodyDiv', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bookFoldPrinting': return { _passthrough: true, kind: 'bookFoldPrinting', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bookFoldPrintingSheets': return { _passthrough: true, kind: 'bookFoldPrintingSheets', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bookFoldRevPrinting': return { _passthrough: true, kind: 'bookFoldRevPrinting', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bordersDoNotSurroundFooter': return { _passthrough: true, kind: 'bordersDoNotSurroundFooter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:bordersDoNotSurroundHeader': return { _passthrough: true, kind: 'bordersDoNotSurroundHeader', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:calcOnExit': return { _passthrough: true, kind: 'calcOnExit', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:calendar': return { _passthrough: true, kind: 'calendar', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:cantSplit': return { _passthrough: true, kind: 'cantSplit', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:caps': return { _passthrough: true, kind: 'caps', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:caption': return { _passthrough: true, kind: 'caption', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:captions': return { _passthrough: true, kind: 'captions', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:category': return { _passthrough: true, kind: 'category', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:cellDel': return { _passthrough: true, kind: 'cellDel', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:cellIns': return { _passthrough: true, kind: 'cellIns', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:cellMerge': return { _passthrough: true, kind: 'cellMerge', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:characterSpacingControl': return { _passthrough: true, kind: 'characterSpacingControl', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:charset': return { _passthrough: true, kind: 'charset', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:checkBox': return { _passthrough: true, kind: 'checkBox', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:checkErrors': return { _passthrough: true, kind: 'checkErrors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:checked': return { _passthrough: true, kind: 'checked', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:citation': return { _passthrough: true, kind: 'citation', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:clickAndTypeStyle': return { _passthrough: true, kind: 'clickAndTypeStyle', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:col': return { _passthrough: true, kind: 'col', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:colDelim': return { _passthrough: true, kind: 'colDelim', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:cols': return { _passthrough: true, kind: 'cols', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:column': return { _passthrough: true, kind: 'column', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:connectString': return { _passthrough: true, kind: 'connectString', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:consecutiveHyphenLimit': return { _passthrough: true, kind: 'consecutiveHyphenLimit', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:contentPart': return { _passthrough: true, kind: 'contentPart', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:contextualSpacing': return { _passthrough: true, kind: 'contextualSpacing', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:continuationSeparator': return { _passthrough: true, kind: 'continuationSeparator', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:control': return { _passthrough: true, kind: 'control', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:cr': return { _passthrough: true, kind: 'cr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:cs': return { _passthrough: true, kind: 'cs', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXml': return { _passthrough: true, kind: 'customXml', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXmlDelRangeEnd': return { _passthrough: true, kind: 'customXmlDelRangeEnd', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXmlDelRangeStart': return { _passthrough: true, kind: 'customXmlDelRangeStart', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXmlInsRangeEnd': return { _passthrough: true, kind: 'customXmlInsRangeEnd', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXmlInsRangeStart': return { _passthrough: true, kind: 'customXmlInsRangeStart', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXmlMoveFromRangeEnd': return { _passthrough: true, kind: 'customXmlMoveFromRangeEnd', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXmlMoveFromRangeStart': return { _passthrough: true, kind: 'customXmlMoveFromRangeStart', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:customXmlPr': return { _passthrough: true, kind: 'customXmlPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dataSource': return { _passthrough: true, kind: 'dataSource', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dataType': return { _passthrough: true, kind: 'dataType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dateFormat': return { _passthrough: true, kind: 'dateFormat', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dayLong': return { _passthrough: true, kind: 'dayLong', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dayShort': return { _passthrough: true, kind: 'dayShort', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:ddList': return { _passthrough: true, kind: 'ddList', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:decimalSymbol': return { _passthrough: true, kind: 'decimalSymbol', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:default': return { _passthrough: true, kind: 'default', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:defaultTableStyle': return { _passthrough: true, kind: 'defaultTableStyle', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:delInstrText': return { _passthrough: true, kind: 'delInstrText', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:description': return { _passthrough: true, kind: 'description', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:destination': return { _passthrough: true, kind: 'destination', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dir': return { _passthrough: true, kind: 'dir', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dirty': return { _passthrough: true, kind: 'dirty', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:div': return { _passthrough: true, kind: 'div', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:divBdr': return { _passthrough: true, kind: 'divBdr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:divs': return { _passthrough: true, kind: 'divs', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:divsChild': return { _passthrough: true, kind: 'divsChild', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotAutoCompressPictures': return { _passthrough: true, kind: 'doNotAutoCompressPictures', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotDemarcateInvalidXml': return { _passthrough: true, kind: 'doNotDemarcateInvalidXml', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotDisplayPageBoundaries': return { _passthrough: true, kind: 'doNotDisplayPageBoundaries', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotEmbedSmartTags': return { _passthrough: true, kind: 'doNotEmbedSmartTags', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotHyphenateCaps': return { _passthrough: true, kind: 'doNotHyphenateCaps', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotOrganizeInFolder': return { _passthrough: true, kind: 'doNotOrganizeInFolder', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotRelyOnCSS': return { _passthrough: true, kind: 'doNotRelyOnCSS', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotSaveAsSingleFile': return { _passthrough: true, kind: 'doNotSaveAsSingleFile', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotSuppressBlankLines': return { _passthrough: true, kind: 'doNotSuppressBlankLines', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotTrackFormatting': return { _passthrough: true, kind: 'doNotTrackFormatting', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotTrackMoves': return { _passthrough: true, kind: 'doNotTrackMoves', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotUseLongFileNames': return { _passthrough: true, kind: 'doNotUseLongFileNames', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotUseMarginsForDrawingGridOrigin': return { _passthrough: true, kind: 'doNotUseMarginsForDrawingGridOrigin', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:doNotValidateAgainstSchema': return { _passthrough: true, kind: 'doNotValidateAgainstSchema', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docGrid': return { _passthrough: true, kind: 'docGrid', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPart': return { _passthrough: true, kind: 'docPart', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPartBody': return { _passthrough: true, kind: 'docPartBody', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPartCategory': return { _passthrough: true, kind: 'docPartCategory', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPartGallery': return { _passthrough: true, kind: 'docPartGallery', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPartList': return { _passthrough: true, kind: 'docPartList', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPartObj': return { _passthrough: true, kind: 'docPartObj', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPartPr': return { _passthrough: true, kind: 'docPartPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docPartUnique': return { _passthrough: true, kind: 'docPartUnique', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docParts': return { _passthrough: true, kind: 'docParts', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docVar': return { _passthrough: true, kind: 'docVar', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:docVars': return { _passthrough: true, kind: 'docVars', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:documentType': return { _passthrough: true, kind: 'documentType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:dynamicAddress': return { _passthrough: true, kind: 'dynamicAddress', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:embedBold': return { _passthrough: true, kind: 'embedBold', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:embedBoldItalic': return { _passthrough: true, kind: 'embedBoldItalic', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:embedItalic': return { _passthrough: true, kind: 'embedItalic', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:embedRegular': return { _passthrough: true, kind: 'embedRegular', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:enabled': return { _passthrough: true, kind: 'enabled', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:encoding': return { _passthrough: true, kind: 'encoding', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:endnote': return { _passthrough: true, kind: 'endnote', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:endnoteRef': return { _passthrough: true, kind: 'endnoteRef', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:endnotes': return { _passthrough: true, kind: 'endnotes', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:entryMacro': return { _passthrough: true, kind: 'entryMacro', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:equation': return { _passthrough: true, kind: 'equation', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:exitMacro': return { _passthrough: true, kind: 'exitMacro', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:fHdr': return { _passthrough: true, kind: 'fHdr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:family': return { _passthrough: true, kind: 'family', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:ffData': return { _passthrough: true, kind: 'ffData', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:fieldMapData': return { _passthrough: true, kind: 'fieldMapData', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:flatBorders': return { _passthrough: true, kind: 'flatBorders', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:font': return { _passthrough: true, kind: 'font', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:fonts': return { _passthrough: true, kind: 'fonts', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:footnote': return { _passthrough: true, kind: 'footnote', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:footnoteRef': return { _passthrough: true, kind: 'footnoteRef', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:footnotes': return { _passthrough: true, kind: 'footnotes', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:forceUpgrade': return { _passthrough: true, kind: 'forceUpgrade', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:formProt': return { _passthrough: true, kind: 'formProt', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:format': return { _passthrough: true, kind: 'format', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:formsDesign': return { _passthrough: true, kind: 'formsDesign', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:frame': return { _passthrough: true, kind: 'frame', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:frameLayout': return { _passthrough: true, kind: 'frameLayout', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:frameset': return { _passthrough: true, kind: 'frameset', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:framesetSplitbar': return { _passthrough: true, kind: 'framesetSplitbar', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:ftr': return { _passthrough: true, kind: 'ftr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:gallery': return { _passthrough: true, kind: 'gallery', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:glossaryDocument': return { _passthrough: true, kind: 'glossaryDocument', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:gridCol': return { _passthrough: true, kind: 'gridCol', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:group': return { _passthrough: true, kind: 'group', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:guid': return { _passthrough: true, kind: 'guid', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:hdr': return { _passthrough: true, kind: 'hdr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:header': return { _passthrough: true, kind: 'header', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:headerSource': return { _passthrough: true, kind: 'headerSource', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:headers': return { _passthrough: true, kind: 'headers', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:helpText': return { _passthrough: true, kind: 'helpText', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:hideGrammaticalErrors': return { _passthrough: true, kind: 'hideGrammaticalErrors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:hideSpellingErrors': return { _passthrough: true, kind: 'hideSpellingErrors', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:hps': return { _passthrough: true, kind: 'hps', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:hpsBaseText': return { _passthrough: true, kind: 'hpsBaseText', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:hpsRaise': return { _passthrough: true, kind: 'hpsRaise', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:hyphenationZone': return { _passthrough: true, kind: 'hyphenationZone', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:ignoreMixedContent': return { _passthrough: true, kind: 'ignoreMixedContent', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:label': return { _passthrough: true, kind: 'label', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:lastRenderedPageBreak': return { _passthrough: true, kind: 'lastRenderedPageBreak', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:latentStyles': return { _passthrough: true, kind: 'latentStyles', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:lid': return { _passthrough: true, kind: 'lid', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:link': return { _passthrough: true, kind: 'link', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:linkStyles': return { _passthrough: true, kind: 'linkStyles', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:linkToQuery': return { _passthrough: true, kind: 'linkToQuery', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:linkedToFile': return { _passthrough: true, kind: 'linkedToFile', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:listEntry': return { _passthrough: true, kind: 'listEntry', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:listItem': return { _passthrough: true, kind: 'listItem', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:listSeparator': return { _passthrough: true, kind: 'listSeparator', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:lnNumType': return { _passthrough: true, kind: 'lnNumType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:lock': return { _passthrough: true, kind: 'lock', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:locked': return { _passthrough: true, kind: 'locked', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:longDesc': return { _passthrough: true, kind: 'longDesc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:lsdException': return { _passthrough: true, kind: 'lsdException', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:mailAsAttachment': return { _passthrough: true, kind: 'mailAsAttachment', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:mailSubject': return { _passthrough: true, kind: 'mailSubject', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:mainDocumentType': return { _passthrough: true, kind: 'mainDocumentType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:mappedName': return { _passthrough: true, kind: 'mappedName', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:marBottom': return { _passthrough: true, kind: 'marBottom', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:marH': return { _passthrough: true, kind: 'marH', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:marLeft': return { _passthrough: true, kind: 'marLeft', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:marRight': return { _passthrough: true, kind: 'marRight', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:marTop': return { _passthrough: true, kind: 'marTop', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:marW': return { _passthrough: true, kind: 'marW', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:matchSrc': return { _passthrough: true, kind: 'matchSrc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:maxLength': return { _passthrough: true, kind: 'maxLength', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:monthLong': return { _passthrough: true, kind: 'monthLong', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:monthShort': return { _passthrough: true, kind: 'monthShort', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:noBorder': return { _passthrough: true, kind: 'noBorder', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:noEndnote': return { _passthrough: true, kind: 'noEndnote', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:noPunctuationKerning': return { _passthrough: true, kind: 'noPunctuationKerning', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:noResizeAllowed': return { _passthrough: true, kind: 'noResizeAllowed', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:notTrueType': return { _passthrough: true, kind: 'notTrueType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:numIdMacAtCleanup': return { _passthrough: true, kind: 'numIdMacAtCleanup', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:numPicBullet': return { _passthrough: true, kind: 'numPicBullet', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:objectEmbed': return { _passthrough: true, kind: 'objectEmbed', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:objectLink': return { _passthrough: true, kind: 'objectLink', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:odso': return { _passthrough: true, kind: 'odso', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:optimizeForBrowser': return { _passthrough: true, kind: 'optimizeForBrowser', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:panose1': return { _passthrough: true, kind: 'panose1', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:paperSrc': return { _passthrough: true, kind: 'paperSrc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:permEnd': return { _passthrough: true, kind: 'permEnd', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:permStart': return { _passthrough: true, kind: 'permStart', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:personal': return { _passthrough: true, kind: 'personal', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:personalCompose': return { _passthrough: true, kind: 'personalCompose', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:personalReply': return { _passthrough: true, kind: 'personalReply', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:pgBorders': return { _passthrough: true, kind: 'pgBorders', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:pgNum': return { _passthrough: true, kind: 'pgNum', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:pgNumType': return { _passthrough: true, kind: 'pgNumType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:pitch': return { _passthrough: true, kind: 'pitch', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:pixelsPerInch': return { _passthrough: true, kind: 'pixelsPerInch', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:placeholder': return { _passthrough: true, kind: 'placeholder', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:pos': return { _passthrough: true, kind: 'pos', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:printFormsData': return { _passthrough: true, kind: 'printFormsData', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:printerSettings': return { _passthrough: true, kind: 'printerSettings', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:proofErr': return { _passthrough: true, kind: 'proofErr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:ptab': return { _passthrough: true, kind: 'ptab', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:qFormat': return { _passthrough: true, kind: 'qFormat', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:query': return { _passthrough: true, kind: 'query', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:readModeInkLockDown': return { _passthrough: true, kind: 'readModeInkLockDown', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:recipientData': return { _passthrough: true, kind: 'recipientData', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:recipients': return { _passthrough: true, kind: 'recipients', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:removeDateAndTime': return { _passthrough: true, kind: 'removeDateAndTime', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:removePersonalInformation': return { _passthrough: true, kind: 'removePersonalInformation', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:result': return { _passthrough: true, kind: 'result', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:rt': return { _passthrough: true, kind: 'rt', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:rtl': return { _passthrough: true, kind: 'rtl', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:rtlGutter': return { _passthrough: true, kind: 'rtlGutter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:ruby': return { _passthrough: true, kind: 'ruby', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:rubyAlign': return { _passthrough: true, kind: 'rubyAlign', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:rubyBase': return { _passthrough: true, kind: 'rubyBase', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:rubyPr': return { _passthrough: true, kind: 'rubyPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:saveFormsData': return { _passthrough: true, kind: 'saveFormsData', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:saveInvalidXml': return { _passthrough: true, kind: 'saveInvalidXml', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:saveSmartTagsAsXml': return { _passthrough: true, kind: 'saveSmartTagsAsXml', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:saveThroughXslt': return { _passthrough: true, kind: 'saveThroughXslt', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:saveXmlDataOnly': return { _passthrough: true, kind: 'saveXmlDataOnly', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:scrollbar': return { _passthrough: true, kind: 'scrollbar', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:sdtEndPr': return { _passthrough: true, kind: 'sdtEndPr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:semiHidden': return { _passthrough: true, kind: 'semiHidden', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:separator': return { _passthrough: true, kind: 'separator', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:showEnvelope': return { _passthrough: true, kind: 'showEnvelope', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:showXMLTags': return { _passthrough: true, kind: 'showXMLTags', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:sig': return { _passthrough: true, kind: 'sig', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:size': return { _passthrough: true, kind: 'size', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:sizeAuto': return { _passthrough: true, kind: 'sizeAuto', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:smartTag': return { _passthrough: true, kind: 'smartTag', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:smartTagType': return { _passthrough: true, kind: 'smartTagType', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:sourceFileName': return { _passthrough: true, kind: 'sourceFileName', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:spaceForUL': return { _passthrough: true, kind: 'spaceForUL', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:src': return { _passthrough: true, kind: 'src', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:statusText': return { _passthrough: true, kind: 'statusText', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:storeMappedDataAs': return { _passthrough: true, kind: 'storeMappedDataAs', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:styleLockQFSet': return { _passthrough: true, kind: 'styleLockQFSet', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:styleLockTheme': return { _passthrough: true, kind: 'styleLockTheme', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:stylePaneFormatFilter': return { _passthrough: true, kind: 'stylePaneFormatFilter', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:stylePaneSortMethod': return { _passthrough: true, kind: 'stylePaneSortMethod', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:subDoc': return { _passthrough: true, kind: 'subDoc', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:summaryLength': return { _passthrough: true, kind: 'summaryLength', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:sym': return { _passthrough: true, kind: 'sym', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:tabIndex': return { _passthrough: true, kind: 'tabIndex', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:table': return { _passthrough: true, kind: 'table', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:targetScreenSz': return { _passthrough: true, kind: 'targetScreenSz', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:tblGrid': return { _passthrough: true, kind: 'tblGrid', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:tblPrEx': return { _passthrough: true, kind: 'tblPrEx', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:tblStylePr': return { _passthrough: true, kind: 'tblStylePr', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:temporary': return { _passthrough: true, kind: 'temporary', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:textInput': return { _passthrough: true, kind: 'textInput', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:title': return { _passthrough: true, kind: 'title', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:trackRevisions': return { _passthrough: true, kind: 'trackRevisions', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:types': return { _passthrough: true, kind: 'types', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:udl': return { _passthrough: true, kind: 'udl', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:uiPriority': return { _passthrough: true, kind: 'uiPriority', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:ulTrailSpace': return { _passthrough: true, kind: 'ulTrailSpace', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:unhideWhenUsed': return { _passthrough: true, kind: 'unhideWhenUsed', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:uniqueTag': return { _passthrough: true, kind: 'uniqueTag', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:useXSLTWhenSaving': return { _passthrough: true, kind: 'useXSLTWhenSaving', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:viewMergedData': return { _passthrough: true, kind: 'viewMergedData', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:webSettings': return { _passthrough: true, kind: 'webSettings', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:yearLong': return { _passthrough: true, kind: 'yearLong', attrs: { ...el.attrs }, children: [...(el.children||[])] };
            case 'w:yearShort': return { _passthrough: true, kind: 'yearShort', attrs: { ...el.attrs }, children: [...(el.children||[])] };
                default: return null;
            }
        }

        function renderElement(obj) {
            if (!obj || !obj.kind) return null;
            switch (obj.kind) {
            case 'active': return xml.el('w:active', obj.attrs || {}, obj.children || []);
            case 'activeRecord': return xml.el('w:activeRecord', obj.attrs || {}, obj.children || []);
            case 'activeWritingStyle': return xml.el('w:activeWritingStyle', obj.attrs || {}, obj.children || []);
            case 'addressFieldName': return xml.el('w:addressFieldName', obj.attrs || {}, obj.children || []);
            case 'adjustLineHeightInTable': return xml.el('w:adjustLineHeightInTable', obj.attrs || {}, obj.children || []);
            case 'adjustRightInd': return xml.el('w:adjustRightInd', obj.attrs || {}, obj.children || []);
            case 'aliases': return xml.el('w:aliases', obj.attrs || {}, obj.children || []);
            case 'alignBordersAndEdges': return xml.el('w:alignBordersAndEdges', obj.attrs || {}, obj.children || []);
            case 'allowPNG': return xml.el('w:allowPNG', obj.attrs || {}, obj.children || []);
            case 'altChunk': return xml.el('w:altChunk', obj.attrs || {}, obj.children || []);
            case 'altChunkPr': return xml.el('w:altChunkPr', obj.attrs || {}, obj.children || []);
            case 'altName': return xml.el('w:altName', obj.attrs || {}, obj.children || []);
            case 'alwaysMergeEmptyNamespace': return xml.el('w:alwaysMergeEmptyNamespace', obj.attrs || {}, obj.children || []);
            case 'alwaysShowPlaceholderText': return xml.el('w:alwaysShowPlaceholderText', obj.attrs || {}, obj.children || []);
            case 'annotationRef': return xml.el('w:annotationRef', obj.attrs || {}, obj.children || []);
            case 'applyBreakingRules': return xml.el('w:applyBreakingRules', obj.attrs || {}, obj.children || []);
            case 'attachedTemplate': return xml.el('w:attachedTemplate', obj.attrs || {}, obj.children || []);
            case 'attr': return xml.el('w:attr', obj.attrs || {}, obj.children || []);
            case 'autoCaption': return xml.el('w:autoCaption', obj.attrs || {}, obj.children || []);
            case 'autoCaptions': return xml.el('w:autoCaptions', obj.attrs || {}, obj.children || []);
            case 'autoFormatOverride': return xml.el('w:autoFormatOverride', obj.attrs || {}, obj.children || []);
            case 'autoHyphenation': return xml.el('w:autoHyphenation', obj.attrs || {}, obj.children || []);
            case 'autoRedefine': return xml.el('w:autoRedefine', obj.attrs || {}, obj.children || []);
            case 'autoSpaceDE': return xml.el('w:autoSpaceDE', obj.attrs || {}, obj.children || []);
            case 'autoSpaceDN': return xml.el('w:autoSpaceDN', obj.attrs || {}, obj.children || []);
            case 'bCs': return xml.el('w:bCs', obj.attrs || {}, obj.children || []);
            case 'background': return xml.el('w:background', obj.attrs || {}, obj.children || []);
            case 'balanceSingleByteDoubleByteWidth': return xml.el('w:balanceSingleByteDoubleByteWidth', obj.attrs || {}, obj.children || []);
            case 'bar': return xml.el('w:bar', obj.attrs || {}, obj.children || []);
            case 'bdo': return xml.el('w:bdo', obj.attrs || {}, obj.children || []);
            case 'bdr': return xml.el('w:bdr', obj.attrs || {}, obj.children || []);
            case 'behavior': return xml.el('w:behavior', obj.attrs || {}, obj.children || []);
            case 'behaviors': return xml.el('w:behaviors', obj.attrs || {}, obj.children || []);
            case 'between': return xml.el('w:between', obj.attrs || {}, obj.children || []);
            case 'bibliography': return xml.el('w:bibliography', obj.attrs || {}, obj.children || []);
            case 'bidi': return xml.el('w:bidi', obj.attrs || {}, obj.children || []);
            case 'bidiVisual': return xml.el('w:bidiVisual', obj.attrs || {}, obj.children || []);
            case 'blockQuote': return xml.el('w:blockQuote', obj.attrs || {}, obj.children || []);
            case 'bodyDiv': return xml.el('w:bodyDiv', obj.attrs || {}, obj.children || []);
            case 'bookFoldPrinting': return xml.el('w:bookFoldPrinting', obj.attrs || {}, obj.children || []);
            case 'bookFoldPrintingSheets': return xml.el('w:bookFoldPrintingSheets', obj.attrs || {}, obj.children || []);
            case 'bookFoldRevPrinting': return xml.el('w:bookFoldRevPrinting', obj.attrs || {}, obj.children || []);
            case 'bordersDoNotSurroundFooter': return xml.el('w:bordersDoNotSurroundFooter', obj.attrs || {}, obj.children || []);
            case 'bordersDoNotSurroundHeader': return xml.el('w:bordersDoNotSurroundHeader', obj.attrs || {}, obj.children || []);
            case 'calcOnExit': return xml.el('w:calcOnExit', obj.attrs || {}, obj.children || []);
            case 'calendar': return xml.el('w:calendar', obj.attrs || {}, obj.children || []);
            case 'cantSplit': return xml.el('w:cantSplit', obj.attrs || {}, obj.children || []);
            case 'caps': return xml.el('w:caps', obj.attrs || {}, obj.children || []);
            case 'caption': return xml.el('w:caption', obj.attrs || {}, obj.children || []);
            case 'captions': return xml.el('w:captions', obj.attrs || {}, obj.children || []);
            case 'category': return xml.el('w:category', obj.attrs || {}, obj.children || []);
            case 'cellDel': return xml.el('w:cellDel', obj.attrs || {}, obj.children || []);
            case 'cellIns': return xml.el('w:cellIns', obj.attrs || {}, obj.children || []);
            case 'cellMerge': return xml.el('w:cellMerge', obj.attrs || {}, obj.children || []);
            case 'characterSpacingControl': return xml.el('w:characterSpacingControl', obj.attrs || {}, obj.children || []);
            case 'charset': return xml.el('w:charset', obj.attrs || {}, obj.children || []);
            case 'checkBox': return xml.el('w:checkBox', obj.attrs || {}, obj.children || []);
            case 'checkErrors': return xml.el('w:checkErrors', obj.attrs || {}, obj.children || []);
            case 'checked': return xml.el('w:checked', obj.attrs || {}, obj.children || []);
            case 'citation': return xml.el('w:citation', obj.attrs || {}, obj.children || []);
            case 'clickAndTypeStyle': return xml.el('w:clickAndTypeStyle', obj.attrs || {}, obj.children || []);
            case 'col': return xml.el('w:col', obj.attrs || {}, obj.children || []);
            case 'colDelim': return xml.el('w:colDelim', obj.attrs || {}, obj.children || []);
            case 'cols': return xml.el('w:cols', obj.attrs || {}, obj.children || []);
            case 'column': return xml.el('w:column', obj.attrs || {}, obj.children || []);
            case 'connectString': return xml.el('w:connectString', obj.attrs || {}, obj.children || []);
            case 'consecutiveHyphenLimit': return xml.el('w:consecutiveHyphenLimit', obj.attrs || {}, obj.children || []);
            case 'contentPart': return xml.el('w:contentPart', obj.attrs || {}, obj.children || []);
            case 'contextualSpacing': return xml.el('w:contextualSpacing', obj.attrs || {}, obj.children || []);
            case 'continuationSeparator': return xml.el('w:continuationSeparator', obj.attrs || {}, obj.children || []);
            case 'control': return xml.el('w:control', obj.attrs || {}, obj.children || []);
            case 'cr': return xml.el('w:cr', obj.attrs || {}, obj.children || []);
            case 'cs': return xml.el('w:cs', obj.attrs || {}, obj.children || []);
            case 'customXml': return xml.el('w:customXml', obj.attrs || {}, obj.children || []);
            case 'customXmlDelRangeEnd': return xml.el('w:customXmlDelRangeEnd', obj.attrs || {}, obj.children || []);
            case 'customXmlDelRangeStart': return xml.el('w:customXmlDelRangeStart', obj.attrs || {}, obj.children || []);
            case 'customXmlInsRangeEnd': return xml.el('w:customXmlInsRangeEnd', obj.attrs || {}, obj.children || []);
            case 'customXmlInsRangeStart': return xml.el('w:customXmlInsRangeStart', obj.attrs || {}, obj.children || []);
            case 'customXmlMoveFromRangeEnd': return xml.el('w:customXmlMoveFromRangeEnd', obj.attrs || {}, obj.children || []);
            case 'customXmlMoveFromRangeStart': return xml.el('w:customXmlMoveFromRangeStart', obj.attrs || {}, obj.children || []);
            case 'customXmlPr': return xml.el('w:customXmlPr', obj.attrs || {}, obj.children || []);
            case 'dataSource': return xml.el('w:dataSource', obj.attrs || {}, obj.children || []);
            case 'dataType': return xml.el('w:dataType', obj.attrs || {}, obj.children || []);
            case 'dateFormat': return xml.el('w:dateFormat', obj.attrs || {}, obj.children || []);
            case 'dayLong': return xml.el('w:dayLong', obj.attrs || {}, obj.children || []);
            case 'dayShort': return xml.el('w:dayShort', obj.attrs || {}, obj.children || []);
            case 'ddList': return xml.el('w:ddList', obj.attrs || {}, obj.children || []);
            case 'decimalSymbol': return xml.el('w:decimalSymbol', obj.attrs || {}, obj.children || []);
            case 'default': return xml.el('w:default', obj.attrs || {}, obj.children || []);
            case 'defaultTableStyle': return xml.el('w:defaultTableStyle', obj.attrs || {}, obj.children || []);
            case 'delInstrText': return xml.el('w:delInstrText', obj.attrs || {}, obj.children || []);
            case 'description': return xml.el('w:description', obj.attrs || {}, obj.children || []);
            case 'destination': return xml.el('w:destination', obj.attrs || {}, obj.children || []);
            case 'dir': return xml.el('w:dir', obj.attrs || {}, obj.children || []);
            case 'dirty': return xml.el('w:dirty', obj.attrs || {}, obj.children || []);
            case 'div': return xml.el('w:div', obj.attrs || {}, obj.children || []);
            case 'divBdr': return xml.el('w:divBdr', obj.attrs || {}, obj.children || []);
            case 'divs': return xml.el('w:divs', obj.attrs || {}, obj.children || []);
            case 'divsChild': return xml.el('w:divsChild', obj.attrs || {}, obj.children || []);
            case 'doNotAutoCompressPictures': return xml.el('w:doNotAutoCompressPictures', obj.attrs || {}, obj.children || []);
            case 'doNotDemarcateInvalidXml': return xml.el('w:doNotDemarcateInvalidXml', obj.attrs || {}, obj.children || []);
            case 'doNotDisplayPageBoundaries': return xml.el('w:doNotDisplayPageBoundaries', obj.attrs || {}, obj.children || []);
            case 'doNotEmbedSmartTags': return xml.el('w:doNotEmbedSmartTags', obj.attrs || {}, obj.children || []);
            case 'doNotHyphenateCaps': return xml.el('w:doNotHyphenateCaps', obj.attrs || {}, obj.children || []);
            case 'doNotOrganizeInFolder': return xml.el('w:doNotOrganizeInFolder', obj.attrs || {}, obj.children || []);
            case 'doNotRelyOnCSS': return xml.el('w:doNotRelyOnCSS', obj.attrs || {}, obj.children || []);
            case 'doNotSaveAsSingleFile': return xml.el('w:doNotSaveAsSingleFile', obj.attrs || {}, obj.children || []);
            case 'doNotSuppressBlankLines': return xml.el('w:doNotSuppressBlankLines', obj.attrs || {}, obj.children || []);
            case 'doNotTrackFormatting': return xml.el('w:doNotTrackFormatting', obj.attrs || {}, obj.children || []);
            case 'doNotTrackMoves': return xml.el('w:doNotTrackMoves', obj.attrs || {}, obj.children || []);
            case 'doNotUseLongFileNames': return xml.el('w:doNotUseLongFileNames', obj.attrs || {}, obj.children || []);
            case 'doNotUseMarginsForDrawingGridOrigin': return xml.el('w:doNotUseMarginsForDrawingGridOrigin', obj.attrs || {}, obj.children || []);
            case 'doNotValidateAgainstSchema': return xml.el('w:doNotValidateAgainstSchema', obj.attrs || {}, obj.children || []);
            case 'docGrid': return xml.el('w:docGrid', obj.attrs || {}, obj.children || []);
            case 'docPart': return xml.el('w:docPart', obj.attrs || {}, obj.children || []);
            case 'docPartBody': return xml.el('w:docPartBody', obj.attrs || {}, obj.children || []);
            case 'docPartCategory': return xml.el('w:docPartCategory', obj.attrs || {}, obj.children || []);
            case 'docPartGallery': return xml.el('w:docPartGallery', obj.attrs || {}, obj.children || []);
            case 'docPartList': return xml.el('w:docPartList', obj.attrs || {}, obj.children || []);
            case 'docPartObj': return xml.el('w:docPartObj', obj.attrs || {}, obj.children || []);
            case 'docPartPr': return xml.el('w:docPartPr', obj.attrs || {}, obj.children || []);
            case 'docPartUnique': return xml.el('w:docPartUnique', obj.attrs || {}, obj.children || []);
            case 'docParts': return xml.el('w:docParts', obj.attrs || {}, obj.children || []);
            case 'docVar': return xml.el('w:docVar', obj.attrs || {}, obj.children || []);
            case 'docVars': return xml.el('w:docVars', obj.attrs || {}, obj.children || []);
            case 'documentType': return xml.el('w:documentType', obj.attrs || {}, obj.children || []);
            case 'dynamicAddress': return xml.el('w:dynamicAddress', obj.attrs || {}, obj.children || []);
            case 'embedBold': return xml.el('w:embedBold', obj.attrs || {}, obj.children || []);
            case 'embedBoldItalic': return xml.el('w:embedBoldItalic', obj.attrs || {}, obj.children || []);
            case 'embedItalic': return xml.el('w:embedItalic', obj.attrs || {}, obj.children || []);
            case 'embedRegular': return xml.el('w:embedRegular', obj.attrs || {}, obj.children || []);
            case 'enabled': return xml.el('w:enabled', obj.attrs || {}, obj.children || []);
            case 'encoding': return xml.el('w:encoding', obj.attrs || {}, obj.children || []);
            case 'endnote': return xml.el('w:endnote', obj.attrs || {}, obj.children || []);
            case 'endnoteRef': return xml.el('w:endnoteRef', obj.attrs || {}, obj.children || []);
            case 'endnotes': return xml.el('w:endnotes', obj.attrs || {}, obj.children || []);
            case 'entryMacro': return xml.el('w:entryMacro', obj.attrs || {}, obj.children || []);
            case 'equation': return xml.el('w:equation', obj.attrs || {}, obj.children || []);
            case 'exitMacro': return xml.el('w:exitMacro', obj.attrs || {}, obj.children || []);
            case 'fHdr': return xml.el('w:fHdr', obj.attrs || {}, obj.children || []);
            case 'family': return xml.el('w:family', obj.attrs || {}, obj.children || []);
            case 'ffData': return xml.el('w:ffData', obj.attrs || {}, obj.children || []);
            case 'fieldMapData': return xml.el('w:fieldMapData', obj.attrs || {}, obj.children || []);
            case 'flatBorders': return xml.el('w:flatBorders', obj.attrs || {}, obj.children || []);
            case 'font': return xml.el('w:font', obj.attrs || {}, obj.children || []);
            case 'fonts': return xml.el('w:fonts', obj.attrs || {}, obj.children || []);
            case 'footnote': return xml.el('w:footnote', obj.attrs || {}, obj.children || []);
            case 'footnoteRef': return xml.el('w:footnoteRef', obj.attrs || {}, obj.children || []);
            case 'footnotes': return xml.el('w:footnotes', obj.attrs || {}, obj.children || []);
            case 'forceUpgrade': return xml.el('w:forceUpgrade', obj.attrs || {}, obj.children || []);
            case 'formProt': return xml.el('w:formProt', obj.attrs || {}, obj.children || []);
            case 'format': return xml.el('w:format', obj.attrs || {}, obj.children || []);
            case 'formsDesign': return xml.el('w:formsDesign', obj.attrs || {}, obj.children || []);
            case 'frame': return xml.el('w:frame', obj.attrs || {}, obj.children || []);
            case 'frameLayout': return xml.el('w:frameLayout', obj.attrs || {}, obj.children || []);
            case 'frameset': return xml.el('w:frameset', obj.attrs || {}, obj.children || []);
            case 'framesetSplitbar': return xml.el('w:framesetSplitbar', obj.attrs || {}, obj.children || []);
            case 'ftr': return xml.el('w:ftr', obj.attrs || {}, obj.children || []);
            case 'gallery': return xml.el('w:gallery', obj.attrs || {}, obj.children || []);
            case 'glossaryDocument': return xml.el('w:glossaryDocument', obj.attrs || {}, obj.children || []);
            case 'gridCol': return xml.el('w:gridCol', obj.attrs || {}, obj.children || []);
            case 'group': return xml.el('w:group', obj.attrs || {}, obj.children || []);
            case 'guid': return xml.el('w:guid', obj.attrs || {}, obj.children || []);
            case 'hdr': return xml.el('w:hdr', obj.attrs || {}, obj.children || []);
            case 'header': return xml.el('w:header', obj.attrs || {}, obj.children || []);
            case 'headerSource': return xml.el('w:headerSource', obj.attrs || {}, obj.children || []);
            case 'headers': return xml.el('w:headers', obj.attrs || {}, obj.children || []);
            case 'helpText': return xml.el('w:helpText', obj.attrs || {}, obj.children || []);
            case 'hideGrammaticalErrors': return xml.el('w:hideGrammaticalErrors', obj.attrs || {}, obj.children || []);
            case 'hideSpellingErrors': return xml.el('w:hideSpellingErrors', obj.attrs || {}, obj.children || []);
            case 'hps': return xml.el('w:hps', obj.attrs || {}, obj.children || []);
            case 'hpsBaseText': return xml.el('w:hpsBaseText', obj.attrs || {}, obj.children || []);
            case 'hpsRaise': return xml.el('w:hpsRaise', obj.attrs || {}, obj.children || []);
            case 'hyphenationZone': return xml.el('w:hyphenationZone', obj.attrs || {}, obj.children || []);
            case 'ignoreMixedContent': return xml.el('w:ignoreMixedContent', obj.attrs || {}, obj.children || []);
            case 'label': return xml.el('w:label', obj.attrs || {}, obj.children || []);
            case 'lastRenderedPageBreak': return xml.el('w:lastRenderedPageBreak', obj.attrs || {}, obj.children || []);
            case 'latentStyles': return xml.el('w:latentStyles', obj.attrs || {}, obj.children || []);
            case 'lid': return xml.el('w:lid', obj.attrs || {}, obj.children || []);
            case 'link': return xml.el('w:link', obj.attrs || {}, obj.children || []);
            case 'linkStyles': return xml.el('w:linkStyles', obj.attrs || {}, obj.children || []);
            case 'linkToQuery': return xml.el('w:linkToQuery', obj.attrs || {}, obj.children || []);
            case 'linkedToFile': return xml.el('w:linkedToFile', obj.attrs || {}, obj.children || []);
            case 'listEntry': return xml.el('w:listEntry', obj.attrs || {}, obj.children || []);
            case 'listItem': return xml.el('w:listItem', obj.attrs || {}, obj.children || []);
            case 'listSeparator': return xml.el('w:listSeparator', obj.attrs || {}, obj.children || []);
            case 'lnNumType': return xml.el('w:lnNumType', obj.attrs || {}, obj.children || []);
            case 'lock': return xml.el('w:lock', obj.attrs || {}, obj.children || []);
            case 'locked': return xml.el('w:locked', obj.attrs || {}, obj.children || []);
            case 'longDesc': return xml.el('w:longDesc', obj.attrs || {}, obj.children || []);
            case 'lsdException': return xml.el('w:lsdException', obj.attrs || {}, obj.children || []);
            case 'mailAsAttachment': return xml.el('w:mailAsAttachment', obj.attrs || {}, obj.children || []);
            case 'mailSubject': return xml.el('w:mailSubject', obj.attrs || {}, obj.children || []);
            case 'mainDocumentType': return xml.el('w:mainDocumentType', obj.attrs || {}, obj.children || []);
            case 'mappedName': return xml.el('w:mappedName', obj.attrs || {}, obj.children || []);
            case 'marBottom': return xml.el('w:marBottom', obj.attrs || {}, obj.children || []);
            case 'marH': return xml.el('w:marH', obj.attrs || {}, obj.children || []);
            case 'marLeft': return xml.el('w:marLeft', obj.attrs || {}, obj.children || []);
            case 'marRight': return xml.el('w:marRight', obj.attrs || {}, obj.children || []);
            case 'marTop': return xml.el('w:marTop', obj.attrs || {}, obj.children || []);
            case 'marW': return xml.el('w:marW', obj.attrs || {}, obj.children || []);
            case 'matchSrc': return xml.el('w:matchSrc', obj.attrs || {}, obj.children || []);
            case 'maxLength': return xml.el('w:maxLength', obj.attrs || {}, obj.children || []);
            case 'monthLong': return xml.el('w:monthLong', obj.attrs || {}, obj.children || []);
            case 'monthShort': return xml.el('w:monthShort', obj.attrs || {}, obj.children || []);
            case 'noBorder': return xml.el('w:noBorder', obj.attrs || {}, obj.children || []);
            case 'noEndnote': return xml.el('w:noEndnote', obj.attrs || {}, obj.children || []);
            case 'noPunctuationKerning': return xml.el('w:noPunctuationKerning', obj.attrs || {}, obj.children || []);
            case 'noResizeAllowed': return xml.el('w:noResizeAllowed', obj.attrs || {}, obj.children || []);
            case 'notTrueType': return xml.el('w:notTrueType', obj.attrs || {}, obj.children || []);
            case 'numIdMacAtCleanup': return xml.el('w:numIdMacAtCleanup', obj.attrs || {}, obj.children || []);
            case 'numPicBullet': return xml.el('w:numPicBullet', obj.attrs || {}, obj.children || []);
            case 'objectEmbed': return xml.el('w:objectEmbed', obj.attrs || {}, obj.children || []);
            case 'objectLink': return xml.el('w:objectLink', obj.attrs || {}, obj.children || []);
            case 'odso': return xml.el('w:odso', obj.attrs || {}, obj.children || []);
            case 'optimizeForBrowser': return xml.el('w:optimizeForBrowser', obj.attrs || {}, obj.children || []);
            case 'panose1': return xml.el('w:panose1', obj.attrs || {}, obj.children || []);
            case 'paperSrc': return xml.el('w:paperSrc', obj.attrs || {}, obj.children || []);
            case 'permEnd': return xml.el('w:permEnd', obj.attrs || {}, obj.children || []);
            case 'permStart': return xml.el('w:permStart', obj.attrs || {}, obj.children || []);
            case 'personal': return xml.el('w:personal', obj.attrs || {}, obj.children || []);
            case 'personalCompose': return xml.el('w:personalCompose', obj.attrs || {}, obj.children || []);
            case 'personalReply': return xml.el('w:personalReply', obj.attrs || {}, obj.children || []);
            case 'pgBorders': return xml.el('w:pgBorders', obj.attrs || {}, obj.children || []);
            case 'pgNum': return xml.el('w:pgNum', obj.attrs || {}, obj.children || []);
            case 'pgNumType': return xml.el('w:pgNumType', obj.attrs || {}, obj.children || []);
            case 'pitch': return xml.el('w:pitch', obj.attrs || {}, obj.children || []);
            case 'pixelsPerInch': return xml.el('w:pixelsPerInch', obj.attrs || {}, obj.children || []);
            case 'placeholder': return xml.el('w:placeholder', obj.attrs || {}, obj.children || []);
            case 'pos': return xml.el('w:pos', obj.attrs || {}, obj.children || []);
            case 'printFormsData': return xml.el('w:printFormsData', obj.attrs || {}, obj.children || []);
            case 'printerSettings': return xml.el('w:printerSettings', obj.attrs || {}, obj.children || []);
            case 'proofErr': return xml.el('w:proofErr', obj.attrs || {}, obj.children || []);
            case 'ptab': return xml.el('w:ptab', obj.attrs || {}, obj.children || []);
            case 'qFormat': return xml.el('w:qFormat', obj.attrs || {}, obj.children || []);
            case 'query': return xml.el('w:query', obj.attrs || {}, obj.children || []);
            case 'readModeInkLockDown': return xml.el('w:readModeInkLockDown', obj.attrs || {}, obj.children || []);
            case 'recipientData': return xml.el('w:recipientData', obj.attrs || {}, obj.children || []);
            case 'recipients': return xml.el('w:recipients', obj.attrs || {}, obj.children || []);
            case 'removeDateAndTime': return xml.el('w:removeDateAndTime', obj.attrs || {}, obj.children || []);
            case 'removePersonalInformation': return xml.el('w:removePersonalInformation', obj.attrs || {}, obj.children || []);
            case 'result': return xml.el('w:result', obj.attrs || {}, obj.children || []);
            case 'rt': return xml.el('w:rt', obj.attrs || {}, obj.children || []);
            case 'rtl': return xml.el('w:rtl', obj.attrs || {}, obj.children || []);
            case 'rtlGutter': return xml.el('w:rtlGutter', obj.attrs || {}, obj.children || []);
            case 'ruby': return xml.el('w:ruby', obj.attrs || {}, obj.children || []);
            case 'rubyAlign': return xml.el('w:rubyAlign', obj.attrs || {}, obj.children || []);
            case 'rubyBase': return xml.el('w:rubyBase', obj.attrs || {}, obj.children || []);
            case 'rubyPr': return xml.el('w:rubyPr', obj.attrs || {}, obj.children || []);
            case 'saveFormsData': return xml.el('w:saveFormsData', obj.attrs || {}, obj.children || []);
            case 'saveInvalidXml': return xml.el('w:saveInvalidXml', obj.attrs || {}, obj.children || []);
            case 'saveSmartTagsAsXml': return xml.el('w:saveSmartTagsAsXml', obj.attrs || {}, obj.children || []);
            case 'saveThroughXslt': return xml.el('w:saveThroughXslt', obj.attrs || {}, obj.children || []);
            case 'saveXmlDataOnly': return xml.el('w:saveXmlDataOnly', obj.attrs || {}, obj.children || []);
            case 'scrollbar': return xml.el('w:scrollbar', obj.attrs || {}, obj.children || []);
            case 'sdtEndPr': return xml.el('w:sdtEndPr', obj.attrs || {}, obj.children || []);
            case 'semiHidden': return xml.el('w:semiHidden', obj.attrs || {}, obj.children || []);
            case 'separator': return xml.el('w:separator', obj.attrs || {}, obj.children || []);
            case 'showEnvelope': return xml.el('w:showEnvelope', obj.attrs || {}, obj.children || []);
            case 'showXMLTags': return xml.el('w:showXMLTags', obj.attrs || {}, obj.children || []);
            case 'sig': return xml.el('w:sig', obj.attrs || {}, obj.children || []);
            case 'size': return xml.el('w:size', obj.attrs || {}, obj.children || []);
            case 'sizeAuto': return xml.el('w:sizeAuto', obj.attrs || {}, obj.children || []);
            case 'smartTag': return xml.el('w:smartTag', obj.attrs || {}, obj.children || []);
            case 'smartTagType': return xml.el('w:smartTagType', obj.attrs || {}, obj.children || []);
            case 'sourceFileName': return xml.el('w:sourceFileName', obj.attrs || {}, obj.children || []);
            case 'spaceForUL': return xml.el('w:spaceForUL', obj.attrs || {}, obj.children || []);
            case 'src': return xml.el('w:src', obj.attrs || {}, obj.children || []);
            case 'statusText': return xml.el('w:statusText', obj.attrs || {}, obj.children || []);
            case 'storeMappedDataAs': return xml.el('w:storeMappedDataAs', obj.attrs || {}, obj.children || []);
            case 'styleLockQFSet': return xml.el('w:styleLockQFSet', obj.attrs || {}, obj.children || []);
            case 'styleLockTheme': return xml.el('w:styleLockTheme', obj.attrs || {}, obj.children || []);
            case 'stylePaneFormatFilter': return xml.el('w:stylePaneFormatFilter', obj.attrs || {}, obj.children || []);
            case 'stylePaneSortMethod': return xml.el('w:stylePaneSortMethod', obj.attrs || {}, obj.children || []);
            case 'subDoc': return xml.el('w:subDoc', obj.attrs || {}, obj.children || []);
            case 'summaryLength': return xml.el('w:summaryLength', obj.attrs || {}, obj.children || []);
            case 'sym': return xml.el('w:sym', obj.attrs || {}, obj.children || []);
            case 'tabIndex': return xml.el('w:tabIndex', obj.attrs || {}, obj.children || []);
            case 'table': return xml.el('w:table', obj.attrs || {}, obj.children || []);
            case 'targetScreenSz': return xml.el('w:targetScreenSz', obj.attrs || {}, obj.children || []);
            case 'tblGrid': return xml.el('w:tblGrid', obj.attrs || {}, obj.children || []);
            case 'tblPrEx': return xml.el('w:tblPrEx', obj.attrs || {}, obj.children || []);
            case 'tblStylePr': return xml.el('w:tblStylePr', obj.attrs || {}, obj.children || []);
            case 'temporary': return xml.el('w:temporary', obj.attrs || {}, obj.children || []);
            case 'textInput': return xml.el('w:textInput', obj.attrs || {}, obj.children || []);
            case 'title': return xml.el('w:title', obj.attrs || {}, obj.children || []);
            case 'trackRevisions': return xml.el('w:trackRevisions', obj.attrs || {}, obj.children || []);
            case 'types': return xml.el('w:types', obj.attrs || {}, obj.children || []);
            case 'udl': return xml.el('w:udl', obj.attrs || {}, obj.children || []);
            case 'uiPriority': return xml.el('w:uiPriority', obj.attrs || {}, obj.children || []);
            case 'ulTrailSpace': return xml.el('w:ulTrailSpace', obj.attrs || {}, obj.children || []);
            case 'unhideWhenUsed': return xml.el('w:unhideWhenUsed', obj.attrs || {}, obj.children || []);
            case 'uniqueTag': return xml.el('w:uniqueTag', obj.attrs || {}, obj.children || []);
            case 'useXSLTWhenSaving': return xml.el('w:useXSLTWhenSaving', obj.attrs || {}, obj.children || []);
            case 'viewMergedData': return xml.el('w:viewMergedData', obj.attrs || {}, obj.children || []);
            case 'webSettings': return xml.el('w:webSettings', obj.attrs || {}, obj.children || []);
            case 'yearLong': return xml.el('w:yearLong', obj.attrs || {}, obj.children || []);
            case 'yearShort': return xml.el('w:yearShort', obj.attrs || {}, obj.children || []);
                default: return null;
            }
        }

        return { parseElement, renderElement, ELEMENTS };
    }
};
