// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: Apache-2.0

// packages/front/fw/integrations/turbopack/index.js
/**
 * @fileoverview Official Turbopack support for `@awacloud/fw`.
 *
 * Turbopack has no JS plugin API (it does not read Webpack plugins), but the
 * `virtual:@awacloud/fw/*` specifier set is fully **enumerable** from
 * `fw.config.json` (presets + side-bundles). So instead of hooking a
 * resolver, this adapter MATERIALIZES each virtual module into a real file
 * (generated at config-evaluation time) and returns a `resolveAlias` map
 * pointing every virtual specifier at its generated file. The emitted code is
 * the same `_shared/core.js` output as every other adapter — direct subpath
 * imports + `registerAllDeep` — so tree-shaking behaves identically.
 *
 * Consumed by the Next.js integration (`withFw` wires the map into
 * `nextConfig.turbopack.resolveAlias`), and usable directly by any
 * Turbopack-based tool that accepts a resolve-alias map.
 *
 * Usage (direct) :
 *
 *     import { fwTurbopack } from '@awacloud/fw/turbopack';
 *     const { resolveAlias } = fwTurbopack({ preset: 'site-interactive' });
 *     // → { 'virtual:@awacloud/fw/preset': './.fw-virtual/preset-default.js', … }
 *
 * Notes :
 *   - The generated directory (default `.fw-virtual/`) is build output —
 *     gitignore it. It is fully rewritten, but LAZILY (BL-299) : merely
 *     calling `fwTurbopack(...)` only reads `fw.config.json` + the catalog
 *     and computes the alias map in memory — it never touches disk. The
 *     rm+mkdir+write only happens the FIRST time the returned `resolveAlias`
 *     is actually read (property access, `Object.keys`, a `{ ...spread }` —
 *     every consumer here, including `../nextjs/index.js`, reads it that way
 *     already) or the returned `materialize()` is called explicitly. Either
 *     trigger is idempotent : the directory is rewritten from scratch once,
 *     on first use, not once per read.
 *   - Sanity is NOT handled here (same stance as the Next integration) :
 *     place it client-side. See ../nextjs/index.js header.
 *
 * @see ../_shared/core.js
 * @see ../nextjs/index.js   wires this into Next ≥ 16 (Turbopack default)
 */

import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { resolve, join } from 'node:path';

import {
    createFwCore,
    VIRTUAL_PRESET_PREFIX,
    VIRTUAL_SIDE_PREFIX,
} from '../_shared/core.js';

const HEADER =
    '// GENERATED by @awacloud/fw/turbopack — do not edit (rewritten on every build).\n';

/**
 * @typedef {Object} FwTurbopackOptions
 * @property {string}   [preset='site']           Default preset for the bare `virtual:@awacloud/fw/preset` specifier.
 * @property {string[]} [sideBundles=[]]          Side-bundles validated up-front.
 * @property {string}   [packageName='@awacloud/fw']   Package specifier used in the emitted imports.
 * @property {string}   [configPath]              Override `fw.config.json` path.
 * @property {string}   [outDir='.fw-virtual']    Directory (relative to cwd) receiving the materialized modules.
 */

/**
 * @typedef {Object} FwTurbopackResult
 * @property {Record<string, string>} resolveAlias  `virtual:@awacloud/fw/*` specifier → generated-file path. Reading ANY property of this object (access, `Object.keys`, a `{...}` spread) lazily triggers materialization — see `materialize()`.
 * @property {string} outDir  Absolute path of the generated directory (not yet created until materialization runs).
 * @property {() => void} materialize  Rewrite `outDir` from scratch and write every planned module to disk. Idempotent (a second call is a no-op). Called automatically the first time `resolveAlias` is read; exposed so a caller can trigger it explicitly instead.
 */

/**
 * Build the Turbopack alias map for the configured virtual modules. Reads
 * `fw.config.json` + the catalog and computes the map ENTIRELY IN MEMORY —
 * this alone never touches disk (BL-299). The directory rm+mkdir+write is
 * deferred to `materialize()`, run lazily on first read of `resolveAlias`
 * (see the `FwTurbopackResult` typedef) so merely constructing the config
 * for inspection can never destroy a pre-existing `outDir`.
 *
 * @param {FwTurbopackOptions} [options]
 * @returns {FwTurbopackResult}
 */
export function fwTurbopack(options = {}) {
    const core = createFwCore(options);
    const outDirRel = options.outDir || '.fw-virtual';
    const outDirAbs = resolve(process.cwd(), outDirRel);

    // Plan every virtual module → generated-file mapping up front. This is
    // PURE : `core.emit` only reads the config/catalog already loaded by
    // `createFwCore` and returns a string — it does not touch disk. Only the
    // `writeFileSync` (and the directory rm+mkdir) below writes anything, and
    // that part is deferred to `materialize()`.
    /** @type {Array<{ file: string, contents: string }>} */
    const plan = [];
    /** @type {Record<string, string>} */
    const target = {};
    /** @param {string} id  @param {string} fileBase */
    const planEntry = (id, fileBase) => {
        const contents = core.emit(id);
        if (contents == null) return;
        const file = `${fileBase}.js`;
        plan.push({ file, contents });
        target[id] = `./${outDirRel.replace(/\\/g, '/')}/${file}`;
    };

    // Bare specifier → the configured default preset.
    planEntry(VIRTUAL_PRESET_PREFIX, 'preset-default');
    for (const name of Object.keys(core.config.presets || {})) {
        planEntry(`${VIRTUAL_PRESET_PREFIX}/${name}`, `preset-${name}`);
    }
    const sideBundles = new Set([
        ...Object.keys(core.config.sideBundles || {}),
        ...(Array.isArray(options.sideBundles) ? options.sideBundles : []),
    ]);
    for (const name of sideBundles) {
        planEntry(`${VIRTUAL_SIDE_PREFIX}/${name}`, `side-bundle-${name}`);
    }

    let materialized = false;
    /**
     * Rewrite `outDirAbs` from scratch and write every planned module — the
     * ONLY place this adapter touches disk. Idempotent: a second call is a
     * no-op, so it is safe to invoke both automatically (via `resolveAlias`
     * access) and explicitly.
     */
    function materialize() {
        if (materialized) return;
        materialized = true;
        // Dedicated, fully-owned directory: rewrite from scratch on first use
        // so renamed presets never leave stale files behind.
        rmSync(outDirAbs, { recursive: true, force: true });
        mkdirSync(outDirAbs, { recursive: true });
        for (const { file, contents } of plan) {
            writeFileSync(join(outDirAbs, file), HEADER + contents);
        }
    }

    // `resolveAlias` looks like — and for every existing consumer here
    // BEHAVES exactly like — a plain object, but reading any of its
    // properties (direct access, `Object.keys`, a `{ ...resolveAlias }`
    // spread, all of which the `nextjs` adapter already does) lazily runs
    // `materialize()` first. Mere construction of `fwTurbopack(...)` never
    // triggers a get/ownKeys trap, so it stays disk-free.
    const resolveAlias = new Proxy(target, {
        get(obj, prop, receiver) {
            materialize();
            return Reflect.get(obj, prop, receiver);
        },
        ownKeys(obj) {
            materialize();
            return Reflect.ownKeys(obj);
        },
        getOwnPropertyDescriptor(obj, prop) {
            materialize();
            return Reflect.getOwnPropertyDescriptor(obj, prop);
        },
    });

    return { resolveAlias, outDir: outDirAbs, materialize };
}

export default fwTurbopack;
