// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: Apache-2.0

/**
 * emit — `*.wasm.js` data-module emitter.
 *
 * Produces a self-contained ESM data module embedding a compiled `.wasm`
 * binary as a base64 literal, per the BATCH_11 task-01 `*.wasm.js`
 * convention (see `packages/front/fw/docs/api/crypto/wasm/runtime.md`).
 *
 * The emitted module:
 *   - has **no imports** and **no import-time side effects** (it only decodes
 *     a base64 string into a `Uint8Array` and exports a frozen descriptor);
 *   - is a **data module** (`type: 'fw.crypto.wasm.data'`), not a registered
 *     fw factory;
 *   - carries provenance in its header (the `SOURCES.md` id / pin) so a binary
 *     can always be traced back to the upstream source it was built from.
 */

import { join } from "node:path";

// ─── Base64 ─────────────────────────────────────────────────────────────────

/**
 * Encode bytes to a base64 string (build-time only; uses Node's Buffer which
 * Bun provides — the *runtime* decoder is the inlined `_b64` below and has no
 * dependency on Buffer).
 */
function toBase64(bytes: Uint8Array): string {
    return Buffer.from(bytes).toString("base64");
}

/**
 * The runtime base64 decoder inlined into every emitted module.
 *
 * Kept dependency-free and side-effect-free so the data module satisfies the
 * fw ESM conventions (no `Buffer`, no `atob` reliance — pure table decode).
 * Exposed here as a string constant so the emitter writes exactly one copy
 * and the unit test can re-import the generated module to verify round-trip.
 */
const B64_DECODER = `const _B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
function _b64(s) {
    const lookup = new Uint8Array(128);
    for (let i = 0; i < _B64.length; i++) lookup[_B64.charCodeAt(i)] = i;
    let len = s.length;
    let pad = 0;
    if (len > 0 && s[len - 1] === '=') { pad++; len--; }
    if (len > 0 && s[len - 1] === '=') { pad++; len--; }
    const out = new Uint8Array(((len * 6) >> 3));
    let p = 0;
    let buf = 0;
    let bits = 0;
    for (let i = 0; i < len; i++) {
        buf = (buf << 6) | lookup[s.charCodeAt(i)];
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out[p++] = (buf >> bits) & 0xff;
        }
    }
    return out;
}`;

// ─── Emit ────────────────────────────────────────────────────────────────────

/**
 * Options describing the provenance recorded in the emitted module header.
 */
export interface EmitProvenance {
    /** The `SOURCES.md` id of the upstream source (e.g. `"argon2-20190702"`). */
    sourceId: string;
}

/**
 * Render the `*.wasm.js` data-module source text for a compiled binary.
 *
 * Pure (no I/O) so it can be unit-tested directly; `emit` wraps it with a
 * file write.
 *
 * @param wasmModule - module file base name (no extension), e.g. `"argon2"`.
 * @param exportName - JS export identifier, e.g. `"argon2Wasm"`.
 * @param bytes      - the compiled `.wasm` bytes.
 * @param simd       - whether the bytes require SIMD (else scalar build).
 * @param provenance - upstream source id for the header (optional).
 * @returns the ESM source text of the data module.
 */
export function renderModule(
    wasmModule: string,
    exportName: string,
    bytes: Uint8Array,
    simd: boolean,
    provenance?: EmitProvenance,
): string {
    const b64 = toBase64(bytes);
    const sourceTag = provenance?.sourceId ? ` (${provenance.sourceId})` : "";
    return `// GENERATED by tools/wasm-crypto — do not edit. Source: SOURCES.md${sourceTag}.
// wasmModule: ${wasmModule}

${B64_DECODER}

export const ${exportName} = {
    name: '${exportName}', type: 'fw.crypto.wasm.data',
    abi: '1', simd: ${simd ? "true" : "false"},
    bytes: _b64('${b64}'),
};
`;
}

/**
 * Write `<outDir>/<wasmModule>.wasm.js` for a compiled binary.
 *
 * @param wasmModule - module file base name (no extension).
 * @param exportName - JS export identifier in the fw crypto layer.
 * @param bytes      - the compiled `.wasm` bytes.
 * @param simd       - whether the bytes require SIMD.
 * @param outDir     - destination directory (created if missing).
 * @param provenance - upstream source id recorded in the header.
 * @returns the absolute path of the written file.
 */
export async function emit(
    wasmModule: string,
    exportName: string,
    bytes: Uint8Array,
    simd: boolean,
    outDir: string,
    provenance?: EmitProvenance,
): Promise<string> {
    const src = renderModule(wasmModule, exportName, bytes, simd, provenance);
    const outPath = join(outDir, `${wasmModule}.wasm.js`);
    await Bun.write(outPath, src);
    return outPath;
}
