// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: Apache-2.0

// packages/front/fw/integrations/_shared/core.js
/**
 * @fileoverview Bundler-agnostic core shared by every `@awacloud/fw` bundler
 * integration (Vite, esbuild, Rollup, Webpack, Bun).
 *
 * It owns the parts that do NOT depend on a specific bundler's plugin API :
 *   - loading + resolving `fw.config.json` (via the shipped `config-resolve.js`),
 *   - reading the committed module catalog (`catalog.generated.json`) to know
 *     each module's binding + file path,
 *   - matching the virtual specifiers,
 *   - emitting the virtual module source (`emit(rawId)`).
 *
 * Both the default config and an `options.configPath` override go through the
 * SAME shipped resolver code path — there is no baked-in vs live divergence.
 * The module catalog is a committed artifact (generated by
 * `bun run integrations:catalog`), so `integrations/**` imports only `node:`
 * builtins + fw files : no dependency on anything under `tools/**`, and fw
 * stays zero-runtime-dep at consume/pack time.
 *
 * Each bundler adapter is then a thin shell that wires its own
 * `resolve`/`load` hooks to `core.isVirtualId` / `core.emit`. The generated
 * code is identical across bundlers : direct subpath imports
 * (`@awacloud/fw/io/codec/hex.js`) + `registerAllDeep`, so tree-shaking and the
 * transitive `deps` closure behave the same everywhere.
 *
 * @see ../vite/index.js   first consumer (reference adapter)
 * @see ../esbuild/index.js
 */

import { readFileSync } from 'node:fs';
import { resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { resolveConfig, injectFullPreset } from './config-resolve.js';

/** Virtual specifier for a pre-instantiated preset runtime. */
export const VIRTUAL_PRESET_PREFIX = 'virtual:@awacloud/fw/preset';
/** Virtual specifier for a side-bundle `install(runtime)` helper. */
export const VIRTUAL_SIDE_PREFIX = 'virtual:@awacloud/fw/side-bundle';

const __filename = fileURLToPath(import.meta.url);
// core.js lives at integrations/_shared/ → package root is three levels up.
const PKG_ROOT = resolve(__filename, '..', '..', '..');
const SRC_DIR = resolve(PKG_ROOT, 'src');
/**
 * Absolute path of the committed module catalog artifact. Exported so a dev
 * host (e.g. the Vite adapter's `configureServer`) can watch it for
 * mid-session regeneration — this constant is the ONLY location the artifact
 * ever lives at, unlike `fw.config.json` which is per-instance overridable
 * via `options.configPath`.
 */
export const CATALOG_PATH = resolve(__filename, '..', 'catalog.generated.json');
const DEFAULT_CONFIG_PATH = resolve(PKG_ROOT, 'fw.config.json');

const CATALOG_MISSING_MSG =
    '[@awacloud/fw] integrations catalog missing/stale — run `bun run integrations:catalog` in packages/front/fw';

/**
 * @typedef {Object} CatalogEntry
 * @property {string} bindingName  The JS export binding (e.g. `hex`).
 * @property {string} file         Absolute path of the module's source file.
 */

/**
 * Read + validate the committed module catalog artifact. Missing file, invalid
 * JSON, or a missing `modules` object all fail with the same actionable
 * regeneration hint (the artifact is a build input, not a runtime asset).
 *
 * @returns {Record<string, { bindingName: string, subpath: string }>}
 */
function loadCatalogModules() {
    let artifact;
    try {
        artifact = JSON.parse(readFileSync(CATALOG_PATH, 'utf8'));
    } catch (err) {
        throw new Error(CATALOG_MISSING_MSG, { cause: err });
    }
    if (!artifact || typeof artifact.modules !== 'object' || artifact.modules === null) {
        throw new Error(CATALOG_MISSING_MSG);
    }
    return artifact.modules;
}

/**
 * @typedef {Object} FwCoreOptions
 * @property {string}   [preset='site']           Default preset for the bare `virtual:@awacloud/fw/preset` specifier.
 * @property {string[]} [sideBundles=[]]          Side-bundles validated up-front (fail fast on misconfiguration).
 * @property {string}   [packageName='@awacloud/fw']   Package specifier used in the emitted imports.
 * @property {string}   [configPath]              Override `fw.config.json` path.
 */

/**
 * @typedef {Object} FwCore
 * @property {import('./config-resolve.js').BuildConfig} config   Live snapshot — re-read `reload()` for the current value (a getter; not stale after `reload()`).
 * @property {Map<string, CatalogEntry>} catalog                  Live snapshot — same freshness note as `config`.
 * @property {string}   pkg
 * @property {string}   srcDir
 * @property {string}   defaultPreset
 * @property {string}   configPath        Resolved absolute path of the `fw.config.json` this core reads (default or `options.configPath`).
 * @property {(id: string) => boolean} isVirtualId   Whether `id` is one of our virtual specifiers.
 * @property {(rawId: string) => (string | null)} emit  Generate the virtual module source for `rawId`.
 * @property {() => void} reload  **Dev-only.** Re-reads `configPath` + the catalog artifact from disk and swaps the cached state, atomically (fully re-validated before anything is mutated, so a broken edit never corrupts a previously-working cache — it throws instead, leaving the prior state intact). Never called by the production/build path, so build output is unaffected by this method's mere existence.
 * @property {(sanity: ('base'|'community'|'lockdown'|false)) => string} sanityImportLine  Import/invoke snippet for the sanity layer (or ''). Every non-`false` tier emits an INVOKING snippet (`import {applyBase|applyCommunity|lockdown} …; <fn>()`), never a bare side-effect import — all three tiers are explicit-call ES modules.
 */

/**
 * The `apply*` export name each explicit-call sanity tier exposes (all tiers
 * except `lockdown`, whose own export IS named `lockdown`).
 *
 * @type {Record<'base'|'community', string>}
 */
const SANITY_APPLY_FN = { base: 'applyBase', community: 'applyCommunity' };

/**
 * Build the shared core : load + resolve config, read the committed catalog,
 * and expose the matcher + emitter. Throws up-front on a missing/invalid
 * catalog artifact, an unknown default preset, or an unknown side-bundle so a
 * misconfiguration fails at plugin construction, not mid-build.
 *
 * The load itself is factored into `loadState()` below so the exact same
 * validated-load logic backs both this one-shot construction AND the
 * dev-only `reload()` seam — there is no separate/diverging "live reload"
 * code path, only the same loader invoked a second time.
 *
 * @param {FwCoreOptions} [options]
 * @returns {FwCore}
 */
export function createFwCore(options = {}) {
    const defaultPreset = options.preset || 'site';
    const sideBundlesUsed = Array.isArray(options.sideBundles) ? options.sideBundles : [];
    const pkg = options.packageName || '@awacloud/fw';
    const configPath = resolve(options.configPath ?? DEFAULT_CONFIG_PATH);

    /**
     * Read + validate config + catalog from disk. Pure w.r.t. this closure's
     * mutable state — returns a fresh `{ config, catalog }` pair without
     * touching anything, so a caller can validate before committing (atomic
     * swap semantics for `reload()`).
     *
     * @returns {{ config: import('./config-resolve.js').BuildConfig, catalog: Map<string, CatalogEntry> }}
     */
    function loadState() {
        // Committed catalog artifact → the internal `name → { bindingName, file }`
        // map the emitters consume (replaces a live `scanAll(SRC_DIR)`).
        const modulesData = loadCatalogModules();
        /** @type {Map<string, CatalogEntry>} */
        const catalog = new Map();
        for (const [name, { bindingName, subpath }] of Object.entries(modulesData)) {
            catalog.set(name, { bindingName, file: resolve(SRC_DIR, subpath) });
        }

        // Config: the SAME shipped resolver for both the default path and an
        // `options.configPath` override — no baked-in vs live divergence.
        const rawConfig = JSON.parse(readFileSync(configPath, 'utf8'));
        const config = resolveConfig(rawConfig);
        // `full` is synthesised from the catalog (same approach as the build orchestrator).
        injectFullPreset(config, modulesData);

        // Up-front validation of the caller's selections.
        if (!config.presets[defaultPreset]) {
            throw new Error(
                `[@awacloud/fw] Unknown preset "${defaultPreset}". Available: ${Object.keys(config.presets).join(', ')}`
            );
        }
        for (const name of sideBundlesUsed) {
            if (!config.sideBundles[name]) {
                throw new Error(
                    `[@awacloud/fw] Unknown side-bundle "${name}". Available: ${Object.keys(config.sideBundles).join(', ')}`
                );
            }
        }
        return { config, catalog };
    }

    let { config, catalog } = loadState();

    /**
     * **Dev-only invalidation seam.** Re-runs `loadState()` and, only if it
     * succeeds, swaps `config`/`catalog` to the fresh values. A malformed
     * edit (bad JSON, unknown preset, …) throws and leaves the previously-
     * working cache untouched — the caller (a dev-server file watcher) is
     * expected to catch and log, not crash the session. Never invoked by the
     * production/build path: nothing here calls `reload()`, so build output
     * is provably unaffected by its mere existence.
     */
    function reload() {
        const next = loadState();
        config = next.config;
        catalog = next.catalog;
    }

    /** @param {string} id */
    function isVirtualId(id) {
        return (
            id === VIRTUAL_PRESET_PREFIX ||
            id.startsWith(VIRTUAL_PRESET_PREFIX + '/') ||
            id.startsWith(VIRTUAL_SIDE_PREFIX + '/')
        );
    }

    /** @param {string} rawId */
    function emit(rawId) {
        if (rawId === VIRTUAL_PRESET_PREFIX) {
            return emitPreset(config.presets[defaultPreset], catalog, pkg);
        }
        if (rawId.startsWith(VIRTUAL_PRESET_PREFIX + '/')) {
            const name = rawId.slice(VIRTUAL_PRESET_PREFIX.length + 1);
            const preset = config.presets[name];
            if (!preset) {
                throw new Error(`[@awacloud/fw] Unknown preset "${name}" requested via virtual import`);
            }
            return emitPreset(preset, catalog, pkg);
        }
        if (rawId.startsWith(VIRTUAL_SIDE_PREFIX + '/')) {
            const name = rawId.slice(VIRTUAL_SIDE_PREFIX.length + 1);
            const sb = config.sideBundles[name];
            if (!sb) {
                throw new Error(`[@awacloud/fw] Unknown side-bundle "${name}" requested via virtual import`);
            }
            return emitSideBundle(sb, catalog, pkg);
        }
        return null;
    }

    return {
        get config() { return config; },
        get catalog() { return catalog; },
        pkg,
        srcDir: SRC_DIR,
        defaultPreset,
        configPath,
        isVirtualId,
        emit,
        reload,
        sanityImportLine: (sanity) => sanityImportLine(sanity, pkg),
    };
}

/**
 * Produce the source snippet that activates the requested sanity tier.
 *
 * All three tiers (`base`, `community`, `lockdown`) are explicit-call ES
 * modules: a bare side-effect import is INERT (proven — W0 FINDINGS §a/§c.1,
 * `bare_import_of_esm_shape_is_INERT`). The snippet must therefore import the
 * tier's named export and invoke it, mirroring the `lockdown` shape that was
 * already correct before this conversion.
 *
 * Exported standalone (not only via `createFwCore(...).sanityImportLine`) so
 * adapters that build their own injected script — e.g. Astro's
 * `injectScript('page', …)`, which bypasses the Vite plugin's `sanity` option
 * — can route through the same emission logic without instantiating a full
 * core (config/catalog load) just for this snippet.
 *
 * @param {('base'|'community'|'lockdown'|false)} sanity
 * @param {string} [pkg='@awacloud/fw']  Package specifier used in the emitted import.
 * @returns {string}
 */
export function sanityImportLine(sanity, pkg = '@awacloud/fw') {
    if (!sanity) return '';
    if (sanity === 'lockdown') {
        return `import { lockdown } from '${pkg}/sanity/lockdown'; lockdown();\n`;
    }
    const fn = SANITY_APPLY_FN[sanity];
    return `import { ${fn} } from '${pkg}/sanity/${sanity}'; ${fn}();\n`;
}

/**
 * Compute the user-facing subpath import specifier for a module file.
 * Maps an absolute path inside `src/` to a `@awacloud/fw/<rel-from-src>` specifier
 * (POSIX-normalised, `.js` extension preserved).
 *
 * @param {string} pkg
 * @param {string} absFile
 * @returns {string}
 */
function subpathSpecifier(pkg, absFile) {
    const rel = relative(SRC_DIR, absFile).replace(/\\/g, '/');
    return `${pkg}/${rel}`;
}

/**
 * Emit a virtual preset module : import each module from its direct subpath,
 * instantiate a `ModuleRuntime`, register them via `registerAllDeep` (the
 * bundler closes the transitive graph through each module file's static
 * imports of its siblings).
 *
 * @param {import('./config-resolve.js').PresetSpec} preset
 * @param {Map<string, CatalogEntry>} catalog
 * @param {string} pkg
 * @returns {string}
 */
export function emitPreset(preset, catalog, pkg) {
    const lines = [
        `// AUTO-GENERATED virtual module — preset "${preset.name}"`,
        `import { ModuleRuntime } from '${pkg}/core/runtime';`,
    ];

    const bindings = [];
    for (const name of preset.modules) {
        const info = catalog.get(name);
        if (!info) {
            throw new Error(`[@awacloud/fw] Module "${name}" listed by preset "${preset.name}" is not in the catalog.`);
        }
        lines.push(`import { ${info.bindingName} } from '${subpathSpecifier(pkg, info.file)}';`);
        bindings.push(info.bindingName);
    }

    lines.push(``);
    lines.push(`export const runtime = new ModuleRuntime();`);
    lines.push(bindings.length
        ? `runtime.registerAllDeep([${bindings.join(', ')}]);`
        : `// empty preset`);
    lines.push(``);
    lines.push(`export const moduleNames = ${JSON.stringify(preset.modules)};`);
    lines.push(``);

    return lines.join('\n');
}

/**
 * Emit a virtual side-bundle module : exposes `install(runtime)` plus a
 * `modules` array, ready to be code-split via dynamic `import()`.
 *
 * @param {import('./config-resolve.js').SideBundleSpec} sb
 * @param {Map<string, CatalogEntry>} catalog
 * @param {string} pkg
 * @returns {string}
 */
export function emitSideBundle(sb, catalog, pkg) {
    const lines = [
        `// AUTO-GENERATED virtual module — side-bundle "${sb.name}"`,
    ];

    const bindings = [];
    for (const name of sb.modules) {
        const info = catalog.get(name);
        if (!info) {
            throw new Error(`[@awacloud/fw] Module "${name}" listed by side-bundle "${sb.name}" is not in the catalog.`);
        }
        lines.push(`import { ${info.bindingName} } from '${subpathSpecifier(pkg, info.file)}';`);
        bindings.push(info.bindingName);
    }

    lines.push(``);
    lines.push(`export const modules = [${bindings.join(', ')}];`);
    lines.push(`export const moduleNames = ${JSON.stringify(sb.modules)};`);
    lines.push(``);
    lines.push(`/**`);
    lines.push(` * Register every module of this side-bundle on the given runtime.`);
    lines.push(` * @param {{ registerAllDeep: (mods: any[]) => any }} runtime`);
    lines.push(` */`);
    lines.push(`export function install(runtime) {`);
    lines.push(`    runtime.registerAllDeep(modules);`);
    lines.push(`}`);
    lines.push(``);

    return lines.join('\n');
}
